== Preface.

In publishing this account of a dearly beloved sister, there is not a great deal,
as editor to perform, more than to write a fair transcript of her own remarks;
till the last few months of her life.
This period does not appear to be recorded by herself;
and the omission is easily accounted for.
She died whilst from home on a religious visit; and having a retentive memory,
it seems to have been her practice, sometimes,
to commit to writing the events of a journey, after her return home.

The Editor has thought he could not better supply the defect in her own narrative,
than by giving some information respecting her last exercising labours,
and by adding an account of the closing scene.

In making an addition to the valuable journals which already exist,
it may not be improper to say, that a peculiar interest is naturally felt,
in the biographical narrations of those with whom we have been acquainted.
Where the writer has held forth, by uniform conduct, the impressive language of,
"`follow me as I have followed Christ,`" this interest is doubly excited;
and has also a powerful tendency to animate survivors,
is the work of righteousness and salvation.

[.signed-section-signature]
William Alexander
