== Chapter I.

[.chapter-subtitle--blurb]
(From her birth to the Eighth month, 1789.)

[.chapter-synopsis]
* Remarks by the Editor, including a testimony concerning her mother
* Her inducement for writing these memoirs
* A remarkable occurrence at ten years old
* Her first impression respecting a gift in the ministry
* On reading the scriptures, plays, and romances
* The death of her father, sister-in-law, and a near friend
* Further exercises respecting the ministry

The subject of these memoirs was born the 7th of the Second month, 1760,
and was the daughter of Dykes and Martha Alexander, of Necdham Market,
in the county of Suffolk.
Her father was in the station of an elder, and her mother in that of a minister.
The decease of the latter, when my sister was about sixteen years of age,
was a heavy loss to her;
as maternal care and tenderness can find many opportunities
of protecting the youthful mind,
which, from the different avocations of the sexes, evade a father`'s most assiduous care.

The reader will be qualified to judge more completely of this loss,
by perusing the following testimony.

[.embedded-content-document.testimony]
--

[.letter-heading]
A short Testimony from Woodbridge Monthly meeting, concerning Martha Alexander:

Our friend Martha Alexander, late wife of Dykes Alexander, of Needham Market,
in the county of Suffolk, was the daughter of John and Abigail Biddle, of Esher in Surry,
both valuable Friends.
Her mother dying when she was young, her father was concerned to educate her,
and the rest of his children, agreeably to their station; especially to bring them up,
according to the living principle of truth,
and in the nurture and admonition of the Lord.

Our deceased friend was born the 13th of the twelfth month, 1726,
and married the 18th of the twelfth month, 1747.
She became early sensible of the reaches of divine grace in her own heart,
and embraced its heavenly visitations.
Earnestly desirous to obtain an abiding therein, she submitted to the cross of Christ,
renouncing the pursuits of vanity and the pleasures of sin;
and walking in circumspection, humility and the fear of the Lord, about the year 1750,
she found her mind concerned to engage in the work of the ministry;
wherein we doubt not but she endeavoured to discharge herself faithfully,
according to her measure.

As she felt her mind drawn in the love of truth,
she visited Friends in divers parts of the nation;
particularly in London and the parts adjacent, in 1752, in company with Mary Kirby;
in the Isle of Ely and there away, 1753, with Margaret Marsham; in the county of Norfolk,
1771, with Mary Gurney; and with the same Friend,
she attended the quarterly meetings of Lincoln and York in 1774;
taking divers meetings in the way both out and home.

She was not usually large in testimony, but very tender, solid, and weighty;
a living example of the doctrines she delivered, in conversation and conduct;
a shining pattern of humility and patience, piety and charity,
faithful and amiable in every relation of life;
affectionately united to the living in Israel; kind and courteous to her neighbours;
sympathizing with the afflicted; and liberal to the needy of all denominations.

She departed this life at her daughter Jesup`'s, in Woodbridge,
the 18th of the ninth month 1775; and her interment was respectfully attended,
both by friends and neighbours, at Needham Market, the 25th of the same.
She was aged near forty-nine, a minister about twenty-five years.`"

--

By comparing these dates,
the reader will find that the writer of these memoirs was
about thirty-eight years old when she thus commenced them.

[.asterism]
'''

Eleventh month 18th, 1798. It is not with the smallest supposition
that any thing I may have to commit to paper,
can be likely to yield either edification or consolation to those who survive me,
that I am induced to attempt to write down some circumstances of my life hitherto:
but I am led to do it, from a belief which sometimes is the companion of my mind,
in solemn seasons, that to look back and consider the merciful,
dealings of a gracious Creator, with one of the least in his spiritual family,
(if worthy to conclude myself at all of this number) and,
as events may be brought afresh to my remembrance, to pen them,
may tend to my own future satisfaction and instruction.

If permitted to continue a few years longer in this state of existence,
I expect to experience a partaking of the cup of mixtures.
Should the bitter draught be more frequently dispensed
than the sweet consolations of His pure spirit,
who is the All-wise Physician,
and who knows best what potion is most convenient to keep the immortal part in health,
and in a state of readiness to receive the crown of eternal life,
may I resignedly accept it,
and increasingly seek for ability to say with the
great pattern of submission:--"`Not my will,
but thine be done.`" Luke 22:42.

At a very early age I believe my mind was, at times,
visited with the heart-tendering power of the Lord;
long before I knew what it was that contrited my spirit before him.
This led me to feel a very great love for such as I esteemed good Friends,
and enabled me to plead their cause when I heard some speak slightly of them,
on account of what were considered singularities.
My education did not subject me to such frequent exposures as fall to the lot of many,
and perhaps of most; yet there were seasons when circumstances of this sort did occur.
One in particular I remember.
When about ten years of age, I rebuked a person,
who was ridiculing one whom I believed to be a valuable woman;
and the person`'s answer to me was--`" I make no
doubt but you will be a preacher when you grow up.`"
I silently received what she said, and felt a secret reward,
which enabled me to rejoice that I was permitted to bear
my little portion of suffering for espousing the good cause.
Yet sorrowful to remember, several years after,
I fear I should have felt less ability to have done it, than at that early period; but,
with reverent thankfulness I can acknowledge the wonderful goodness of a merciful God,
who never permitted me to go long unrebuked,
when I had wandered widely from his holy guidance.

About the seventeenth year of my age, as I was sitting in a meeting at Woodbridge,
I saw clearly, that if I was faithful, I should, after a time,
be entrusted with a gift in the ministry.
Notwithstanding my having been so favoured,
I went afterwards much further from the simplicity of my guarded education,
in divers respects, than I had done before; but mercy followed me so nearly and closely,
that at times my heart was sad,
though I was not guilty of any thing which many thought much amiss of,
for a young person.
I indulged however in many inclinations and propensities,
which required to be slain by the sword of the Lord,
before I could be brought into a state of acceptance with Him.

At length my desires were earnest to witness redemption from the world;
and in the twenty-third year of my age, one first-day evening,
after I came from a neighbouring meeting, in a solid frame of mind,
I went into my chamber, and taking up the bible,
opened it at the seventh chapter of the Revelations, and read the last two verses:
"`They shall hunger no more, neither thirst any more;
neither shall the sun light on them, nor any heat;
for the Lamb which is in the midst of the throne shall feed them,
and shall lead them unto living fountains of waters;
and God shall wipe away all tears from their eyes.`"
On reading this passage my mind was so opened to
view this precious state of departed spirits,
and I believe, for a short space so permitted to participate their joy, that Peter like,
I desired I might build a tabernacle, or, in other words,
continue in this blessed situation.
However I was not allowed to abide long here;
for as he was instructed to hear the beloved Son of God, so it was given me to see,
if ever I became of that happy number, I also must hear Him who "`endured the cross,
despising the shame;`" Heb. 12:2,
and must experience a willingness wrought in my heart,
to fill up my measure of sufferings for the precious cause.

Soon after this time,
I was permitted to share largely in the gospel labours
of several of the Lord`'s anointed messengers;
who were wonderfully led to minister to my state,
and proved that they were commissioned to preach the gospel of
glad tidings to such as were seeking a city that hath foundations;
which I humbly trust was my situation.
Among those who were thus made helpful to my poor soul,
was my beloved friend William Matthews, of York Town, Pennsylvania,
whose fatherly attention and notice, in so needful a season,
will ever render the remembrance of him dear to me;
while preservation is mercifully granted to abide
faithful to the requisitions of a gracious Creator.

When my mind became thus far awakened,
and was seeking a better and more enduring substance than had heretofore been my experience,
how was my soul often contrited before my heavenly Father,
both in meetings and in retirement at home.
He very frequently caused my cup to overflow,
so that my heart was melted into such a state of humiliation before him for past offences,
as to enable me frequently to cry unto him, that his eye might not spare,
until all within me was brought into subjection to his divine will.
At this time I was favoured to receive much comfort in reading the Holy Scriptures,
which I often Took up when alone, to my consolation and encouragement.
Then, deeply did I lament that any of my precious time had been
spent in perusing publications of an unprofitable tendency;
such as plays and romances;
and I was made sensible that nothing I had ever been in the practice of,
had so much alienated my mind from the love and fear of God,
or led me so far from the simplicity of the pure truth, as books of this kind.
How often did I wish I could warn the whole world of their pernicious effects,
and especially the young people in our own Society.
Penning this remark brings to my remembrance, how in an instant,
I was entirely weaned from ever desiring again to look into a book of this description.
It was by a few words expressed by a beloved friend,
when I was about reading to her one night after we got up stairs,
and were retiring to bed.
She queried with me, and I believe under divine influence, "`Dear Mary,
is such a subject likely to profit us upon our pillows?`"
The question so forcibly struck my mind, that I very willingly laid down the volume,
and to the best of my remembrance, I never more read a page in that,
or any thing of the like kind,
I have often thought those few words were indeed
"`like apples of gold in pictures of silver.`" Prov. 25:11.

In the fourth month of the year 1786, my dear father was removed from us by death,
after an illness of several months;
during which time my mind was often favoured with the consolating presence of him,
who is strength in weakness to his dependent children.
This enabled me to pass through that trying dispensation
in a manner I could not have expected;
yet, after the final close of my beloved earthly parent,
it pleased my heavenly Father to try me with the loss of spiritual enjoyment also;
and for a long time, my poor mind was often in a very distressed situation,
"`Tossed with tempest, and not comforted.`" Isaiah 54:11.
Indeed this was a time of sorrow both within and without;
for that day nine weeks on which my father expired, my dear sister Elizabeth Alexander,
my brother Samuel`'s wife, breathed her last,
and left a disconsolate husband and four tender children,
besides many other near connections, to mourn her loss.

Thus bereaved of beloved relatives,
my brother William and myself agreed to continue together in our father`'s house;
and my brother Samuel was favoured with the company and assistance of his wife`'s aunt,
Mary Gurney, who, from that time, resided with him and his dear children.
I believe she was made a blessing to many of us,
while we were permitted to have her society amongst us;
which was till the autumn of the year 1788, when,
after having been out several weeks on religious service,
she was taken ill at her cousin Joseph Cockfield`'s, at Upton, and in a few days,
departed this life, I fully believe, in peace with her God,
having spent her last days in advocating his holy cause.^
footnote:[Among the extracts from letters, added to Sarah Grubb`'s journal,
is one peculiarly descriptive of this valued relative.--Dated twelfth month, 1788.]

Though a little out of the order of time, I may here observe,
that on the 7th of Sixth month, 1787,
was my final parting with William Matthews and Rebecca Wright,
gospel messengers of peculiar good to my mind.

To return to my own situation:
My poor mind was long kept in a state of great inward want,
and I was sometimes ready to conclude my God had forgotten to be gracious.
In such seasons, I have been willing to offer up all unto him and his service,
so that I might again taste of his goodness: and in this time of trial,
I did give up many things which I believed he called for.

Whilst in this situation, I had sometimes to believe, that if I stood faithful,
it would be required of me publicly to espouse that pure cause, which,
notwithstanding all my exercises,
I could feel was more precious to me than the increase of any outward comforts;
but the removal of my before-mentioned beloved friend, Mary Gurney, at such a juncture,
was so great a trial of my faith and confidence,
that I was almost ready to conclude it would now
be impossible for me ever to break through;
though I did earnestly covet resignation to the divine will therein.
In this situation of mind I attended her burial, and though, I believe, at her grave,
I might have publicly borne testimony of my belief in her happy change; yet,
as I did not willfully disobey what, I have since apprehended, was a divine intimation,
I did not feel much condemnation.
It was some months after this before I again felt as much as I did at that time; yet,
frequently was I in great doubt and uneasiness, often feeling, as I thought,
something to communicate, when in religious opportunities;
but fearing I should begin in the great work of public ministry before the right time,
I withheld speaking.
At other times, both at meetings and at home, both by day and by night,
I was under very great exercise lest I should be entirely mistaken,
and that what I felt should not be any right call to the ministry.

This was my situation one night in the beginning of the year 1789, when,
after having lain a considerable time in close exercise of spirit,
a light shined round my bed, and I heard a voice intelligibly say:
"`Thou art appointed to preach the Gospel.`"
Immediately the light disappeared, and I was left in an awful, thankful frame of mind;
esteeming it an intimation granted by Him,
who alone knows the deep conflicts of spirit I then experienced,
lest I should engage in his cause without his command.
Yet, even after this mark of divine condescension to my poor doubting mind,
being sincerely desirous of abiding the full time
in the furnace preparatory for so important a work,
it was many weeks before I opened my lips, in what I considered the work of the ministry.
The first time, was in the fifth month of this year,
in a religious opportunity in my brother Samuel`'s family, I believe,
in nearly the following words: "`When Peter in his vision,
wherein he saw the sheet let down from heaven,
with that great variety of living creatures,
and heard a voice commanding him to kill and eat, refused,
fearing he should do wrong in so doing; he, after his refusal,
heard the voice again saying unto him.
What God hath cleansed or sanctified, that call not thou common.`"

After I had uttered these sentences,
my soul was filled with the incomes of heavenly consolation to such a degree,
as I never before had experienced,
which I humbly received as a token of Divine approbation for my evening`'s sacrifice.
Indeed so quiet and peaceful was my mind for many days after,
that I was ready to conclude "`the bitterness of death was past;`" 1 Sam. 15:32;
that I never again should feel the distressing conflicts which I had long endured;
and that my having thus far surrendered my will to the divine will, would be accepted,
and I never again might feel a necessity of the like nature.
But I soon felt a similar engagement in meetings,
though not with as much clearness and strength as that evening,
and therefore did not venture to speak until it was equally strong.

About ten weeks after the before-mentioned time, on the first-day of the week,
and 26th of the seventh month, 1789, in our forenoon meeting,
I felt a very powerful intimation to stand up and express a few words,
and put out my hand to lay hold of the seat which stood before me;
but even then I drew back my hand and gave it up;
for which I felt much more condemnation than I ever had done before under like circumstances;
and went home in very great distress of mind,
which I feared I should not be able to conceal from
my brother William while I sat at dinner with him.
Whether he did discover my situation or not, I cannot tell:
but as soon as the table cloth was removed, I retired to my chamber,
and there made covenant with Him, whom I sorrowfully felt I had offended by my omission,
that if He would be mercifully pleased to try me in the afternoon, with some new opening,
I would give up; fearing, if it were the same as in the morning,
that I might move too much from my own feelings at that time,
without a sufficient renewal of life.
And, oh! the unspeakable condescension of a gracious Creator,
when he sees the integrity of the heart.
I had not been seated many minutes in meeting,
before the petition of Caleb`'s daughter was brought so forcibly, with such clearness,
and in such a confirming manner before me,
that I could not doubt its being given me for communication:
but it was so early in the meeting, I thought I must endeavour to bear my burden awhile,
yet earnestly begged I might be enabled to speak in the right time.
While I was under these awful impressions, a Friend got up, and had a lively opportunity,
though I knew not much of what he said; for indeed my own exercise at that time,
seemed all I could attend to.
As soon as he sat down, I stood up and began with the before-mentioned petition:
"`Thou hast given me a south land;
give me also springs of water;`" and after commenting a little upon it,
I sat down full of peace.

This was twelve or thirteen years after I first saw
a prospect of receiving a call to the ministry,
as I sat in a meeting at Woodbridge; and after this,
which I then apprehended to be a clear intimation of the divine will concerning me,
it was some years before I had any further serious impressions respecting it.
The transition from tribulation to joy which my mind experienced on my return home,
from the afternoon meeting, was such as led me to crave of my heavenly Father,
that he would be pleased to grant me ability to follow
him faithfully in the way of his holy requirings,
from time to time.
For some weeks after my soul was often enabled secretly to praise the Lord,
as on the banks of deliverance; which encouraged me to hope,
notwithstanding all my foregoing omissions,
that He who sees the bent and intent of every heart,
knowing my exceeding great fear of going too fast, had passed by my offences,
and was now confirming to my mind, that to serve him without reserve,
was the way to ensure comfort here, as well as everlasting happiness hereafter.
Indeed I fully believe,
that while it is really a solid fear of running before the Lord sends,
which keeps back any sacrifice he is calling for, especially in this important work,
there is less danger in tidying the fleece again and again,
than in running too hastily forward; even when a living engagement is felt:
but to be preserved from erring on either hand,
is a blessing which can be witnessed only while the
mind is engaged to keep near to its only sure director,
the unerring principle of Truth, and submits to be unreservedly guided thereby.

From such considerations, I have often felt thankfulness raised in my heart,
that while my mind was under the weighty exercises
which preceded my appearance in the ministry,
and which I believe some of my feeling friends, in the vision of light,
were permitted to behold, they used such great caution in intimating the subject to me,
as seldom to give me reason to suppose they had any apprehension of my real situation.
I believe that minds thus circumstanced,
are better left to the guidance of Him who begins the work, to carry it on,
and bring forth fruit in his own season; even though, through fear or care,
a state of jeopardy may be somewhat prolonged;
rather than that any injudicious interference of others,
should bring the poor tribulated soul out of the preparatory furnace,
before the appointed baptisms are fulfilled.

I am fully aware,
that the doubting mind may sometimes be rightly encouraged to obedience,
by the countenance of those who have had larger experience of the great
Master`'s dealings with his humble and truly dependent followers;
but I believe, beyond all doubt,
that a much greater number have suffered by being injudiciously drawn forth,
before the full accomplishment of all the dispensations
which the Lord sees meet for them to pass through.
