== Chapter IV.

(22nd of Eleventh month, 1795, to the 8th of Second month, 1796.)

A meeting at Walton--Debenham--Writes to a Friend imprisoned on account of tithes.

Some Friends feeling their minds drawn towards the inhabitants of Walton in this county,
our monthly meeting appointed a meeting to be held there,
on first-day the 22nd of the eleventh month this year.
It proved a season owned in a very precious manner, by the great Master of assemblies;
and some of our hearts were bowed in humble thankfulness,
under a sense of his gracious goodness, and returned home in peace.

1796+++.+++ For several of the latter weeks in last year, my mind was very closely tried,
with an apprehension of its being required of me,
to have a meeting with the inhabitants of Debenham in this county.
As the impression appeared to ripen, it proved a very weighty circumstance to me,
not knowing of any one who felt a similar concern.
+++[+++ was brought under great exercise, lest I should move in this important work,
in a false zeal, unbidden by the great and good Minister of ministers;
and I earnestly coveted to receive some undoubted evidence of its rectitude,
before I attempted to mention it to my friends.
This was mercifully granted,
and the day and hour for holding the meeting pointed out with such clearness,
that I could not doubt the evidence received.
At our monthly meeting, in the first month this year,
I laid the subject before my friends;
who affectionately sympathized with me in my prospect; and feeling unity therewith,
the men`'s meeting appointed a committee,
to provide a suitable place for holding the meeting in, on the 19th of this month.
The committee, with several other Friends, accompanied me there at the time fixed.
My brother Samuel and my dear friend Martha Brewster, were of the number,
and were fellow-labourers in the gospel mission.
We were favoured to have an open meeting, and I think I may say,
parted with the people in much good will; some of them, I believe, having been reached,
under the prevalency of the power of the great Shepherd and bishop of souls.
My mind was permitted to experience, for some weeks after, a sabbath of rest;
which was cause of thankful rejoicing, having previously past some time of deep anxiety;
yet, I think I was not insensible, under this change of situation,
of the necessity of watching, lest I should take my flight upon the sabbath day.
I believe that after the mind has been strengthened to perform any act of dedication,
which yields a portion of peace,
there is great need to guard against erring on this hand.
Yea, surely! under every dispensation of a gracious and all-wise providence,
there is occasion to crave ability to maintain a constant dependence upon Him,
and on the guidance of his good Spirit.

When at York in the autumn of last year, I visited several Friends,
imprisoned in the castle there, for refusing to pay priests`' demands.
Not fully clearing my mind, at that time, of the sympathy and solicitude I felt for them,
and after my return home, receiving an acceptable letter from one of their company,
I wrote an answer; from which the following is an extract,
dated the 8th of the second month this year.

Mary Alexander to Joseph Browne

Dear Friend.

Having frequently felt my mind bended towards thyself,
and thy companions in outward bonds since I passed
a little time with you in your prison house,
it was very grateful to receive thy token of kind remembrance.
It renewed my sympathy towards thyself in particular,
believing thou art often secretly coveting that the precious cause, for which you suffer,
may not be let fall, in the smallest degree, through unwatchfulness,
in any of those who have so avowedly espoused it,
as to submit themselves to be separated from their nearest outward connections,
rather than baulk the testimony given them to bear to the great Minister of ministers;
without whose divine aid, none can really profit the people by their ministry.
And oh! that all you who have thus given up your names to reproach,
may be willing to remember, that there is need to seek after daily bread,
even in your obscure dwelling;
and to feel the sustaining arm of never-failing power to be near,
not only to support the mind in a cheerful submission
to the present trial of faith and patience,
but also to afford a portion of strength to go in and out before the people,
within the walls of that place.
Many of them, I am ready to believe, from my past and present feelings,
are looking towards your little company;
and if all are concerned singly to eye the Captain of our salvation,
your suffering may tend to the exaltation of the
precious name of Jesus in the hearts of some of them.
I have also believed, dear Friends, that it is the gracious design of our Holy Head,
if this is your individual concern,
so to sanctify this afflictive dispensation to some of you,
as thereby to enlarge your inward acquaintance and communion with Himself; yea,
to increase your store of durable riches and righteousness.

And thou, my friend, with whom I am particularly corresponding--situated as thou art,
amidst such a mixture of irreligious characters,
as inhabit the different apartments in your prison;
I make no doubt but thy feeling mind is, at times, introduced into spiritual bondage;
and perhaps darkness may be the covering thereof,
in sympathy with the pure seed in the hearts of others;
and thy conflicts and exercises may be many and various.
Notwithstanding this may be thy frequent experience, I trust thou art, at other times,
admitted to that peaceful retreat,
where the Lord`'s table is spread with the dainties of his own house,
and which is an ample compensation for many deep probations.
And I believe thou wilt be favoured with a continuance of the like sustaining power:
for truly he is not wanting in compassion to his depending dedicated children; but,
unto such, a morsel of food will be handed in due season.

+++[+++Of this friend Joseph Browne, the following account is given in Piety Promoted.

In the present day, when it may at least be said, that liberality of sentiment,
and mutual allowance for difference of judgment, on religious matters,
prevail in a degree unknown in the times when our
pious forefathers first engaged the attention,
and drew upon themselves the abuse of their countrymen,
it is rare to find any one suffering imprisonment for ecclesiastical causes.
But as in the life of Joseph Browne we have an instance, and not a solitary one,
of such being the case,
a concise sketch of the attendant circumstances may
not be improperly introduced in this place.

Joseph Browne was an inhabitant of that retired part of the West riding of Yorkshire,
called Lothersdale,
where he endeavoured to maintain a wife and a large family of children,^
footnote:[At the time of his commitment he had ten children;
but they were not all dependent on him for support.]
by the laborious trade of constructing dry stone fences,
so common in that and other rocky parts of England.
He also occupied a small quantity of land; but with all his efforts, was but little,
or scarcely above want.
He was a man generally respected,
and about his thirty-first year had come forth in the ministry,
with the acceptance of his friends.
Notwithstanding his poverty,
he was nearly a constant attender of his monthly and quarterly meetings,
generally performing the journey on foot.
He twice attended the Yearly meeting in London,
where I remember to have observed with pleasure the simplicity of his manners and appearance.

"`In or about the year 1781, he, with several other Friends, was summoned,
at the suit of the Vicar of Carlton, in which parish he lived,
for not having paid his small tithes, which amounted,
as appeared by a subsequent inquiry, to about thirty-four shillings annually,
and were consequently far within the limits of the power of a warrant from a justice.
The magistrates before whom he appeared, judging the alledged demand exorbitant,
recommended a more moderate claim; but the prosecutor refused to abate,
and commenced an Exchequer process.
This, after long delays,
produced a decree which determined the average amount
of nine years tithe to be nearly as above stated.^
footnote:[Viz.
nine years, 15£. 4s. Od. Iq.--One year, 1£. 13s. 9d. 3q.]
The costs were above half as much more.
For not complying with this decree, in the fifth month 1795,
he was committed to York Castle, together with seven others,
his neighbours and partners in the defence of the suit,
as also at length in imprisonment.
The names of his fellow prisoners are, John Wormall, John Stansfield, Henry Wormall,
Henry King, John Wilkinson, William Hartley, and James Walton;
most of them in low circumstances,
and all of them dependent on their own industry for support:
the withdrawing of which threw the families of some
of them upon the charity of their friends for relief.

How long they would have remained prisoners, is hard to say.
I do not recollect that any attempt was made to sequester their property;
and had this been attempted,
it is probable that the property of some of them
would not have been sufficient for the demand,
costs, and expenses.
At length, however, in consequence of a representation to the king,
stating the suffering case of several of his peaceable subjects,
and the continued delay of the plaintiff; a clause was inserted in an act of parliament,
empowering certain magistrates to terminate this oppressive case;
by which means (except John Wilkinson,
who had died in the jail) they were liberated after something less than two years confinement;
and distraints were made on their property,
to the satisfaction of the examining magistrates.
It may be proper to add, that they were kindly treated in the castle,
and generally pitied by most that heard the case.

The Friends of the quarterly meeting of Yorkshire,
in their testimony concerning this Friend, observed that,
though he was much afflicted with infirmity of body (for he laboured
under a pulmonary complaint,) and various deep exercises of mind,
both before, during, and after his imprisonment; yet he was enabled through all,
to evince much patience, and resignation of spirit.
In the course of his religious labours, say they,
he had frequently to encourage others to a like dependence
on the arm of everlasting help,
as well as to strengthen Friends in the support of their various testimonies,
particularly that for which he had so deeply suffered.
He departed this life the 28th of the sixth month, 1803, aged about fifty-two years,
having been a minister about twenty-one years.

A few days before his departure, some Friends called on him,
previously to setting out for the quarterly meeting.
He told them that he also had thought of attending it; "`but,`" added he,
"`we are short sighted creatures.`"
He desired his dear love to Friends,
and remarked that he never felt more love to them than at that time;
and that he was easy, and resigned to the will of Providence,
who had been wonderful in goodness, and had supported him through many difficulties,
to his own admiration: so that he had to rejoice, even in tribulation.
He added, that whether it should please the Lord to take him at that time,
or to restore him again, he was easy as to the event.

Thus it appears that peace and love attended his close;
and where peace and love lake up their abode,
it would not be an irreverent strain of expression to say, that heaven is begun.

Oh! that every awakened soul would daily seek after the sweet influences of gospel love!
It sweetens society; it begets its likeness in others; it excites gratitude;
and even if bestowed on the ungrateful (as saith our dear Redeemer,
love`'s holy and exhaustless fountain, the rain falls on the just and on the unjust),
it brings its own sweet reward with it; for it attracts the approbation of God.
Where then will be contempt?
where the indulgence of evil surmisings, and hard thoughts?
where, either studied or careless detraction?
where, even the needless disclosure of real failings?
where the least place for any enmity?

These hurtful practices, and pride, the promoter of many of such practices,
will fall before the prevalence of pure Christian love; and surely,
when these are exterminated from the heart,
is it not so far prepared for its best and most sacred purpose,
to be a temple of the holy Spirit?
Amen!
