== Chapter V.

[.chapter-subtitle--blurb]
(Ninth month, 1796, to the Third month, 1798.)

[.chapter-synopsis]
* Her brother William`'s marriage, etc.
* Visits some meetings in company with S. Harrison and S. Birkbeck
* Deep conflict of mind
* Visit to the Principality of Wales, etc.
* Yearly meeting at Welch-Pool
* Coalbrook Dale
* Left her sister Ann at London yearly meeting
* Joined her again at Plaistow
* Visits Herefordshire, etc.
* Macclesfield quarterly meeting, Wrexham in Wales
* Account of their visit to the Principality
* Melksham
* Is ill there
* Goes to Cirencester and returns home
* A dream
* Settles in her new habitation

In the ninth month this year, 1796, my brother William married my beloved friend Ann Tuke.
Previously to their marriage,
they kindly proposed my continuing a resident in their family after it; but,
on considering the subject, I felt most easy to decline their affectionate offer:
though not without an intention of staying with them for some months after their union;
which I accordingly did.

Our friend Sarah Harrison, of Philadelphia, accompanied by Sarah Birkbeck, of Settle,
in Yorkshire, was, in the latter part of this year, in our county.
Besides visiting all the meetings of Friends, she had many among other people,
and divers of them where no Friends meetings had been remembered before.
Having looked towards some of the places with a similar prospect,
before her coming this way, it was relieving to my mind,
to have the opportunity of accompanying her, and her companion,
to several of the said meetings; and also to a few in Essex.
In the third month, 1797, I met them again, in Essex,
was with them at two or three more public meetings,
and was favoured in the close to feel peace.

Very soon after these engagements, my mind had to experience much inward want,
indeed to pass through a season of deep conflict, and of sore exercise;
wherein it seemed to me as though my soul`'s enemy was let loose,
with an unlimited power to buffet me at his will.
Never had I known my faith and confidence in Infinite Goodness so nearly overcome before.
Almost continually, for several weeks,
was my mind in a state comparable to being "`Tossed with tempest,
and not comforted,`" Isaiah 54:11, and left without one grain of lively hope,
which might have been as an anchor to the soul.

Some of my near connections were sensible that my situation was a trying one,
yet none knew how bitter was the anguish I felt, but He who knows all things.
My health became impaired, and at times,
I was ready to conclude I should sink away under the exercise I felt;
though without any degree of cheering hope that my
sufferings would end with my natural life.
Could I have once believed this, oh! how should I have coveted such a release.
But, peradventure, had this belief been experienced,
I might have felt less ability to have sought after
patient resignation to bear the present trial;
though I am fully convinced,
I was often too apt to cast away my confidence in holy help and
not enough careful to abide at all times on the watch-tower;
nor always willing enough to stay in the ward this whole dark night.
Alas! how hardly does the creaturely part bend to suffering.

During this season of close exercise with me,
my sister Ann at our monthly meeting in the third month, opened a prospect she had,
of paying a religious visit to the Principality of Wales, and counties adjacent.
For several years, I had had a similar prospect, and some months before,
had believed we should unite in this journey; yet, now, all former views were closed,
and I could see no way to move forward;
and earnestly did I covet to be preserved from warming
myself by the sparks of my own kindling,
or putting forth my hand unbidden in so important a work.
Yet having passed through some very trying seasons,
I was made willing thereby to be any thing or nothing, so that I might again experience,
"`the Lord to lift up his countenance upon me, and give me peace.`" Num. 6:26.
When I felt any thing like a willingness of this sort,
oh! how did the cruel accuser endeavour to insinuate,
that I had already overacted my part,
in being too forward to lend a hand in what I had thought the Lord`'s work;
and thereby had incurred his displeasure, wounded my friends,
and brought this state of spiritual death over my own mind.
But boundless mercy was pleased now,
sometimes to afford a little portion of his calming influence, which, in some degree,
stilled the boisterous waves and enabled me, at times, to look forward with hope,
that I should again be permitted to experience the animating
rays of "`the Sun of righteousness,`" Mal. 4:2,
to dispel the thick darkness in which my poor mind had been, and still was enveloped.

In this situation I went to our monthly meeting in the fourth month,
where I ventured to inform my friends what my farmer views had been,
and that within a short time they had appeared to be reviving,
but I thought them still so faint,
I desired to cast myself entirely upon them to judge for me.
This I did under a greater sense of weakness than
I had ever opened any thing of the like nature before;
yet it so far made its way with the meeting, as to get a liberation at that time,
for me to visit the Principality of Wales, and counties adjacent.

My sister Ann and myself, left home together, accompanied by my brother William,
on the 16th of the fourth month, and went to Bury;
intending for the Welch yearly meeting, to be held the following week, at Welch-Pool,
in Montgomeryshire.
On our way we passed through Kettering, in Northamptonshire, and Coalbrook Dale,
in Shropshire, and attended meetings there.
On third-day the 25th of fourth month, we got to Welch-Pool; and on fourth, fifth,
and sixth days, was held the yearly meeting there.
At the close thereof, not seeing our way as we had expected,
to proceed in our visit to the Principality, we concluded to return to Coalbrook Dale,
and accordingly got back to Shrewsbury on seventh-day.
My sister stopped by the way to have a meeting that afternoon,
at a small village we passed through in going; but, finding myself very unwell,
and not feeling any thing in my own mind for the meeting, I went on;
and left her in company with our dear friends Deborah Darby, Rebecca Young, and others.

On first-day we attended a morning meeting at Shrewsbury,
in which I was favoured to feel a little strength, to relieve my mind,
of an exercise I had felt for some individuals then present whom I had seen,
and felt for before at Welch-Pool.
In the evening we had a public meeting,
which for a considerable time was very exercising,
yet in the close afforded some satisfaction.
On second-day we came back to Coalbrook Dale.
Third-day, we attended the weekday meeting there,
in which neither of us had any thing to communicate;
but in the course of the meeting I thought I saw clearly,
that we must go from house to house among them; and after meeting,
I mentioned it to my sister, who I then found, had had a similar prospect.

This evening we had a public meeting at a neighbouring village.
From fourth-day the 3rd of the fifth month, to fourth-day the 10th of the same,
in company with our beloved friend Rebecca Young,
we visited the families of Friends in the meetings of Newdale and Coalbrook Dale,
in which my brother, who was still with us, united;
and his company and help were very acceptable to us.
A few sittings I was prevented attending from indisposition;
and in some others I sat under great suffering, both of body and mind,
so much so that I was, at times, ready to doubt the rectitude of my having left home;
yet I had, at others,
the satisfaction of seeing my beloved companions were rightly engaged,
which tended to bear up my drooping mind;
having been in some sort the means of encouraging them to give up to this service.
Though, in the performance thereof, I was but of little help to them; yet, in the close,
I believe none of us had cause to repent giving up
to what we had apprehended to be a required duty.

Fifth-day the 11th, I stayed at Coalbrook Dale, being very unwell;
and my sister had a public meeting at a place at a short distance,
and returned to me after it.

Sixth-day.
We had not, either of us,
been able to come at any satisfactory clearness respecting our future movements,
till this morning, when I thought a little light arose in my mind,
with a pointing towards Cheshire, which we were glad to accept.
Our dear friends Deborah Darby and Rebecca Young intending
to set out this afternoon for London yearly meeting,
and having appointed a public meeting to be held this evening at Bridgenorth,
we accompanied them there, expecting the next day to part with them at that place;
and take meetings from thence in our way into Cheshire, and so into Wales.
But my sister not feeling easy to part with them there,
we went on with them till second-day, and parted with them at Campden.

After this we again moved on towards Wales, and for a few days pretty satisfactorily;
till my sister`'s mind became so closely arrested for the
approaching yearly meeting to be held in London,
that it seemed safest to turn about, and endeavour to get there as early as we could,
with taking meetings in our way.

[.small-break]
'''

+++[+++To be thus led about,
and so frequently turned from the object at which they were aiming,
as was on several occasions, their experience in this journey,
proved no small trial to my beloved sister; yet, I have reason to believe,
this humiliating dispensation, was peculiarly and lastingly instructive to her mind.
To move in a feeling of weakness, and with such a portion of light,
as could not reflect its beams on distant objects,
but only just mark the present step with a safe degree of clearness,
though very trying to the creature, teaches humble and full dependence on the Creator.]

[.small-break]
'''

We arrived in London two days after the commencement of the yearly meeting;
but I did not feel my mind at all bound to it, and still found my health, at times,
much affected, therefore, after staying one day in London, I returned home,
where I passed about ten days in peace, and found my health much recruited.

On second-day the 5th of sixth month, I left home again and went to Colchester,
where I met my brother William, who had parted with sister Ann that morning,
at or near London, and was then on his way home.
On third-day evening I met my sister at Plaistow.
Sixth-day we left the neighbourhood of London, and went into Hertfordshire,
agreeably to a prospect I had before I left home this time:
having expected it might be right for us to take a few meetings in that county,
and from thence proceed pretty directly for Wales.
But our views were again protracted; for after we got into that quarterly meeting,
my sister felt her mind engaged to go through it,
and also to visit some other of the midland counties, previously to our entering Wales.

Though I did not feel my mind so much bound to this prospect,
yet I could not see my way to leave her;
and therefore thinking it most consistent with gospel order,
we unitedly addressed our monthly meeting for further credentials,
and obtained the concurrence of our friends at home,
to proceed as in the openings of truth might appear right.

[.small-break]
'''

+++[+++Their peculiar situation excited much sympathy in the monthly meeting;
and being attended with a feeling of near unity with their extended concern,
their friends were induced to give them such a certificate
as would fully liberate them to any service in this land.]

[.small-break]
'''

After visiting divers counties, on the 13th and 14th of the ninth month,
we attended the quarterly meeting held at Macclesfield, for Cheshire and Staffordshire.
There we opened our prospect of visiting the Principality of Wales;
hoping some of our brethren might feel bound to accompany us;
expecting to be engaged in public meetings in many parts very distant from any Friends.
And our much-valued friend Joseph Storrs, from Chesterfield in Derbyshire, being present,
felt a willingness to accompany us; as did two friends of that quarterly meeting,
George Jones and Olive Sims, who all met us at Chester on the 23rd.

On the 25th we entered Wales,
at the place I had had a prospect of more than four months before,
when we were at Coalbrook Dale; and that evening had a meeting there,
viz. Wrexham in Denbighshire.
This meeting was large,
and I believe there was a great variety of states among the people then gathered;
some of whom were seriously disposed.
Indeed, I think in the future movements through this Principality, in a more general way,
we met with a larger proportion of religious, seeking minds,
than in most of the counties we visited in England.
Yet many even of those, we had often to fear,
were too much seeking the living among the dead;
not enough inward in their search after durable riches;
nor enough acquainted with the one essential baptism of the Holy Ghost and fire; which,
if suffered to operate, would consume all that is of an unsubstantial nature.
However,
to meet with here and there one who was so far submitting to bear the cross of Christ,
as to become willing to follow him, not only out of many of the vanities of the world,
but also out of many unsubstantial rites and ceremonies, and who was seeking him,
where alone he is to be found, in the secret of the heart;
was consoling to our often drooping minds.
I trust, some there are, who, if they are faithful to the day of small things, will,
in due time, be made rulers over more; know their spiritual borders enlarged,
and their acquaintance with the Beloved of souls increased.
That this may become their happy experience, is what I often coveted when with them,
and oft-times since, when far distant from them.

We were in Wales about eight weeks,
were in all the counties both of North and South Wales;
and besides visiting the few meetings of Friends, had upwards of forty public meetings,
many of them in places where it could not be remembered
that any Friends meetings had been held before.
We very generally met with civil treatment from the inhabitants;
and travelled nearly eight hundred and fifty miles in that mountainous country.

Soon after we got into Wales, for nearly two weeks, at times,
I was very unwell in my health;
whereby I was prevented attending two public meetings on the Isle of Anglesea,
and two meetings of Friends on a first-day at Llwyndw in Merionethshire.
Here our whole company was detained several days
at the house of our kind friend Henry Owen,
on account of my indisposition; but after a little rest there,
I was enabled to go through the remaining part of this close travel in good health.
My dear sister was favoured to experience a continuance of health during the whole time;
but, near the close, she was permitted to know a very trying depression of spirits,
so much so as nearly to disqualify her for any public service,
which greatly added to my trials.
Yet I was mercifully strengthened to keep up both in body and mind,
to the end of our engagements in that Principality.

When we had finished our visit in Wales, I believe, in sympathy with her,
I soon got into the same situation;
so that it seemed safest for us to leave a few meetings
we had once expected to take in Herefordshire,
and go directly from Leominster, in that county, to Melksham, in Wiltshire.
Our dear brother Samuel and his daughter Lucy, were there,
on a visit to his daughter Martha;
who a few weeks before had been married so Thomas Jeffreys of that place.
We arrived at their house on first-day evening, the 26th of the eleventh month.
Our kind companions left us at different times; O. Sims at Caermarthen in South Wales,
on the 30th of the tenth month; G. Jones at Leominster,
on the 23rd of the eleventh month; and J. Storrs after we got to Melksham.

Very soon after we got to Melksham,
my mind was much relieved from the deep depression I had
felt for some days previously to our getting there:
but my sister was rather longer before she experienced the same relief; yet,
in a few days, she was favoured also to feel the depression much removed,
and a pointing in her mind towards Warminster, a place in the neighbourhood,
at which she had missed having a public meeting when
she was in the county a considerable time before.
The meeting was appointed on sixth-day evening, the 1st of the twelfth month,
which I attended,
and we were accompanied by our dear brother S. A. In this meeting and after it,
I was very unwell.
We got back to Melksham the next day, where I took some suitable medicine;
which did not afford so much relief as to enable me to attend their meeting on first-day.

In the evening my brother finding me more unwell,
was desirous of my taking some medical advice;
which I submitted to for his and the rest of my relations`' satisfaction.

That night I was very ill indeed;
sometimes I was almost ready to conclude it might be the final close of all things here;
especially when I considered the deep conflict of mind which
both my sister and myself had lately experienced;
and that my mind had been entirely relieved from any further
prospect of religious service ever since I left Wales;
not only during that very trying dispensation, but also now,
when favoured with a very different one; wherein all was serenity and peace.
In this situation,
had it not been for the trial I apprehended it would be to my dear niece,
Martha Jeffreys, to have a circumstance so awful take place under her roof,
so soon after her settlement there; I could willingly, yea, I think I may say,
gladly have exchanged mortality for immortality at that time;
if it had been consistent with the good pleasure of Him in whom is all power.
He is able to cause even a sick bed to become pleasant; yea, desirable,
if in that situation the poor finite understanding is more expanded,
and the mind more quickened to behold the marvellous dealings of an all-wise Creator!
This I think I can with humble gratitude acknowledge was, at times,
my experience on this bed of sickness: and I was enabled to desire,
whether life or death should be my portion, that His will might be done.
However, after a few days I got so much better, as to think of moving from Melksham,
when my brother and sister were at liberty so to do, who, during my illness,
had engaged together in visiting the families of Friends there.

After taking an affectionate leave of our kind relations,
who had very tenderly cared for me in my illness,
we all left their house on fourth-day the 13th,
and went to Cirencester in Gloucestershire;
where we were kindly received by our friends Samuel and Sarah Bowley.
The next morning my brother Samuel and his daughter Lucy set off for home,
and left my sister and myself there.
Though I was favoured to bear travelling the day before, twenty-seven miles,
with less fatigue than might have been expected; yet,
after having parted with my brother and niece, I was that day very unwell.
Continuing so, and not feeling any command to go forth again into the field of labour,
I believed it was safest for me to decline attending any of the meetings in that neighbourhood,
with my sister, who left me for a few days, and accompanied by Ann Bowley,
visited some places adjacent and returned to me again.

As I did not improve in my health by longer rest, but rather grew weaker,
we thought it best to inform our relations at home how we were circumstanced;
and my brother William came to us at very short notice,
intending to continue with his wife till she saw her way clear to return home.
My dear brother and sister D. and H. Alexander very
kindly came to us in a few days`' after him,
intending to accompany me home as speedily as my
very weak situation would admit of my travelling.
On fourth-day, the 3rd of the first month, 1798, my brothers and sisters, and myself,
all left Cirencester, where I had been very affectionately nursed for three weeks,
at the house of my kind friends before mentioned, and went to Burford.

The next day William and Ann Alexander left me there; and the day following,
accompanied by my brother Dykes and his wife,
I went twenty-nine miles further on my way home.
On the 9th we reached Walworth, where I was taken more unwell again,
having rather mended in travelling till this time:
and was detained there till seventh-day the 13th,
at the house of our friends Richard and Jane Harris; who, with their whole family,
manifested much affectionate kindness,
of which I desire ever to retain a grateful remembrance.
On third-day the 16th, we reached Needham;
where my mind was favoured to partake of a portion of enriching peace;
and a tribute of thankful acknowledgment was raised in my
heart to the great Dispenser of every good.

My health gradually improved from this time;
yet it was some months before I fully regained my usual strength.

One night while I was ill at Cirencester, I dreamed that I had departed this life,
and was admitted into happiness;
but I met with only one whom I knew or had ever known in the body, and she, I was told,
was just admitted, and was to continue there, for she had finished her day`'s work;
but as I had not, I must return to the body,
and if faithful to what was manifested from time to time,
I should be admitted again when the work appointed me to do was fully accomplished.
My mind being awfully impressed with what had occurred in my sleep,
in the course of the next day I told it to Sarah Bowley.
Very soon after,
we heard that the Friend whom I had seen in my dream was very dangerously ill;
and before I got home, I was informed of her decease;
and I have no reason to doubt but she is admitted into everlasting rest and peace.
Oh, that the blessing of preservation may be my experience,
that so the place prepared may be happily mine, when time to me shall be no more!

At our monthly meeting in the third month,
my sister Ann and myself gave up our certificates.
And the day following, viz. on fourth-day the 7th of the third month, 1798,
I entered into my present habitation;
which was mercifully permitted to be a very peaceful home,
for some weeks after I first settled therein.
