== Chapter XII.

(21st of seventh month, 1808, to the 27th of eighth month, 1809.)

Parts with her nephews W. H. A. and J. A.--with her sister Ann and brother William.--Visit
to heads of families in her own monthly meeting.--York.--Returns home through Lincolnshire.

1808+++.+++ Fifth-day, the 21st of seventh month.
This day William Henry Alexander, and his brother Joseph, left Needham for Broughton.
A separation which, to my affectionate feelings, is very pinching,
having no expectation of ever seeing much more of them.
They have always been exceedingly dear to me for their beloved parents`' sake;
and at present, there is much in the precious boys also to attach me closely to them.
The prayer of my heart is, that whatever may be their future allotment in life,
if they should be permitted to arrive at a state of maturity,
they may be preserved within the limitations of the pure truth,
and so dedicated to the most noble cause,
as to be found worthy to become standard-bearers in our Israel, when many of those,
who now feel the weight of the Ark of our testimonies resting on their shoulders,
shall be called from works to rewards.
Amen.

At Bury, on the 21st of the ninth month, I took leave of my beloved sister Ann Alexander,
under a feeling of very near regard; she intending to go forward thence towards York.
This was another parting which very closely tried my tenderest feelings;
but a degree of quiet which I believe was not at my own command,
accompanied my mind in my journey home, which was cause of humble gratitude to Him,
who is able to say unto the troubled sea, "`Peace,
be still;`" Mark 4:39. It is a pleasant reflection,
that during the time of our residing in the same place,
a precious harmony was uniformly maintained between us; and much do I desire,
that though we are now likely to be far separated in body,
we may know that durable cement, true unity of spirit,
which is the bond of lasting peace.

On fifth-day afternoon, the 13th of tenth month,
my beloved brother William Alexander left Needham, his native place,
with a prospect of settling at York.
This was to me a closely trying separation,
from one to whom by the ties of natural affection,
and the still more uniting bond of religious kinship, I have, from early life,
to the present time, felt very nearly attached.
His removal with that of his endeared companion in life, and their precious children,
has made a chasm in our domestic circle here,
which I cannot expect ever to see filled up to me; yet, as I believe,
my beloved brother and sister,
are entrusted with qualifications adapted to their new situation,
I feel something which forbids my repining at the loss, which, as an individual,
I have sustained by their departure; though I have felt, and still do feel,
so intimately bound to them, that the separation is one of my most bitter cups.
But though these dear objects of my love are so far removed,
as to preclude all probability of much more sweet and social intercourse with them,
I am fully aware that I have cause still to number my remaining blessings,
both in a religious and domestic point of view.
And my heart`'s desire is, to stand so unreservedly dedicated to the Author of them all,
as to feel a capacity to know, what I shall render for his multiplied favours.^
footnote:[As her own memorandums furnish but few
remarks on the period contained in this chapter,
the following extract from a letter to a near relative, dated 21st of twelfth month,
1808, may be acceptable to the reader.
After stating that a heavy fall of snow had prevented
many Friends from getting to the quarterly meeting,
particularly from the western side of the county, she says,
"`We had not one from that quarter in the select meeting,
and not a representative in the women`'s meetings though four were appointed.
Thou wilt suppose such a deprivation just now,
must prove particularly trying to some of us.
Indeed I cannot describe what my feelings were,
when I found how our little company was likely to be deserted:
but^ with thankfulness we may acknowledge,
though we were deprived of divers of our friends,
whose presence would have gladdened our hearts,
yet the great President of our assemblies condescended
to afford a renewal of his ancient goodness,
and enabled some of our spirits to bow in reverence at his sacred footstool,
and implore the continuance of his fatherly protection.`"]

1809+++.+++ Third-day, the 10th of the first month.
I have lately been engaged with divers other Friends,
by appointment of our monthly meeting,
in compliance with a recommendation of the last yearly meeting,
in paying a visit to the heads of families,
on the important subject of the fourth query.^
footnote:[This query, which is the third to Women Friends, is as follows,
viz.--`"Do Friends endeavour, by precept and example, to train up their children,
servants, and those under their care, in a religious life and conversation,
consistent with our Christian profession, in the frequent reading of the Holy Scriptures,
and in plainness of speech, behaviour and apparel?`"]
Though I have not felt the weight of the work so to rest upon my shoulders,
as I believe it has rested on some of my fellow-labourers; yet,
since the close of the engagement,
I have been permitted to review my movements with them,
in a degree of humble confidence that it was my desire,
when I could do nothing for the promotion of the cause which I love more than life,
I might be preserved from doing any thing, that could, in any wise,
weaken the hands of those with whom I have been banded,
and to whom I felt bound in near gospel fellowship.
And I believe, in the close of our visit, we have, individually and unitedly,
had cause to acknowledge that a portion of solid satisfaction has been
the recompense of our resignation to this delegation of the church.

Fourth-day, 21st of sixth month.
Though my present motive in leaving home is a social
visit to my endeared relatives at York,
yet I feel desirous of dwelling so near to the pure spring of eternal excellency,
as to be permitted to accompany with the incorruptible seed of the kingdom;
whether in suffering or rejoicing:
and I crave the blessing of preservation both in heights and in depths.

First-day, 27th of eighth month.
Last fifth-day evening I reached home, after an absence of nine weeks and one day.
Greatest part of the time has been spent with my dear brother and sister at York.
My brother S. Alexander, met me at Ackworth general meeting,
and I returned with him to York; after which we left the county by Hull and Thorne;
and from the latter went into Lincolnshire, where we visited all the meetings except two,
which were taken by my brother, in his way into Yorkshire.
In leaving home, I had no expectation of engaging in religious service;
yet my beloved brother going out with a prospect of visiting the above meetings,
and intimating it to our monthly meeting,
I have felt well satisfied with the opportunity of accompanying him therein.
I trust some of the little flock, where our lots have been cast,
have been encouraged to pursue the one thing needful, with increasing vigilance;
and our own minds strengthened renewedly to acknowledge
the goodness and mercy of a faithful Creator,
who is ever ready to uphold in every season of trial, his humbly dependent children.
