== Chapter II.

[.chapter-subtitle--blurb]
(1790 to Twelfth month, 1793.)

[.chapter-synopsis]
* Her condition after appearing in the ministry
* Visit to a friend
* Acknowledged as a minister
* Visit to families at Woodbridge and Ipswich
* Norwich Quarterly Meeting
* Deep exercises of mind
* Beccles Monthly Meeting
* Bury Monthly Meeting
* Woodbridge Monthly Meeting

In the course of the first twelve months after I opened my mouth in meetings,
I was permitted to experience many different dispensations.
Some of them were seasons of very great desertion of all good,
which led me often to a close searching of heart,
to know whether I kept pace with my heavenly Guide,
or whether I ran before or stayed behind him in my little religious movements.
I think it was not often that my heart condemned me; but when it did,
it was for omission rather than for commission.
My soul often coveted the blessing of resignation to the divine will,
that I might be enabled to endure all the turnings
and overturnings of his holy hand upon me;
so that I might be thereby prepared to accomplish
the work he should be pleased to assign me,
in his house and family; if worthy to be esteemed the smallest of his dedicated servants.

In the autumn of this year, 1790, for many weeks, at times,
I was brought into a secret engagement, and I trust I may say, according to my measure,
travail of soul, on account of a Friend in this county who, I fully believe,
had been an anointed minister of the gospel; but through unwatchfulness,
his brightness was much eclipsed.
At length my feelings were so closely arrested,
as to lead me to apprehend I should not get clear of the exercise I felt on his account,
without going to pay him a visit, though many miles distant;
which I made known to my brother Samuel, who kindly accompanied me,
in the forepart of the twelfth month.
Although I know not that the visit availed much to the individual,
yet I was favoured with strength to relieve my own mind, and came home in peace.

1791+++.+++ In the fourth month of this year,
I was recommended to our select monthly meeting as a minister in unity.
This circumstance brought a very heavy exercise over my mind,
fearing Friends had not had sufficient proof of my religious movements,
to warrant their noticing me after this manner; and earnest were my cries to Him,
who I humbly hoped had put me forth in so awful a vocation,
that he would be pleased to grant such a portion of the blessing of preservation,
as to enable me to move forward without bringing any dishonour on his pure cause.
And oh! may a care of this sort, be ever the attendant of my mind,
under all the various dispensations of an unerring Providence;
seeking more and more after ability, so to steer along through this probationary state,
as that "`neither principalities, nor powers, nor things present, nor things to come,
nor height, nor depth, nor any other creature,
may be able to separate`" my poor soul "`from the
love of God which is in Christ Jesus our Lord.`"
Rom. 8:38, 39. Such a care is needful to preserve, from time to time,
in unreserved obedience to all His divine requisitions.

In the eleventh month this year, I visited,
in company with a committee of our monthly meeting,
the families of Friends in Woodbridge;
and though it was not much that was required of me, yet, in a few families,
I felt my heart enlarged in gospel love, beyond what I had heretofore experienced;
and in the close was favoured to feel solid satisfaction.
Some of the committee being about to engage in a similar visit at Ipswich,
a week or two after, I thought I felt it my duty to unite with them again; yet,
many were my fears lest I should be mistaken in my feelings,
thinking that possibly what I then felt, might arise,
only from a degree of sympathy with some of my beloved friends of the committee;
and not being one myself,
it seemed to require a clearer evidence than if I had been under the appointment,
though it was left open for any Friend of the monthly meeting to join,
who felt the weight of the service.
For one so little experienced in the important work to make a second attempt,
under such circumstances, I thought would be looked upon to be rather forward;
and indeed I sometimes feared,
that my getting through at Woodbridge with a good degree of satisfaction,
might too readily encourage me to go forth again,
without a sufficient commission from Him who puts forth his own, and goes before them.
I coveted permission to try the fleece both wet and dry,
which I think was mercifully granted; and I joined my friends in a humble hope,
that whether it should please my great and gracious
Master to employ me in advocating his precious cause,
or permit me silently to visit the pure seed in the hearts of his people,
I might be able to say in sincerity, "`Your will be done.`"
Abundant cause have I to acknowledge the goodness of an All-powerful Creator,
who proved himself to be strength in my weakness,
and granted the riches of his love to be eminently shed among us, in several families;
whereby he mercifully evinced that he was both able
and willing to be unto his dependent children,
a present help in the needful time.
A portion of that peace which surpasses every other consideration,
was felt in my return home; and raised a tribute of thankfulness in my heart unto Him,
to whom I desire ever to render the praise of his own works.

In the latter end of this year, in company with my brother Dykes Alexander,
and two other Friends, I attended Norwich quarterly meeting;
and though we were not permitted to experience any great aboundings of heavenly good,
yet I trust we were strengthened by the Shepherd of Israel,
to visit the oppressed seed in captivity in that city.
After the meeting closed, on fourth-day afternoon, the 28th of twelfth month,
we left the place in peace, and went to Yoxford that night.
The next morning we went to Woodbridge,
and attended the burial of our much-valued friend, Martha Steward, there that day;
in the evening went to Ipswich; and on sixth-day morning I came to Needham.

For some weeks after my return home, my mind was, at times,
richly replenished with the incomes of my heavenly Father`'s love,
so that I could indeed "`rejoice in the Lord,
and joy in the God of my salvation,`" Hab. 3:18. But,
alas! when a very different dispensation was permitted,
which was my experience by far the greater part of the year 1792, then, oh then!
I found it hard work,
and many times altogether impossible to acknowledge with the prophet,
that "`although the fig-tree shall not blossom, neither shall fruit be in the vines;
the labour of the olive shall fail, and the fields shall yield no crop;
the flocks shall be cut off from the fold, and there shall be no herd in the stalls:
yet I will rejoice in the Lord, I will joy in the God of my salvation.`" Hab. 3:17-18.
Fully convinced I was of the truth of David`'s declaration,
where he says, "`Your people shall be willing in the day of your power:`" Psal.
110:3; and in that day only,
I saw it was that the poor frail mind could be brought into a state of resignation,
to receive its appointed portion of suffering for the precious cause sake.
Yes, I was sometimes mercifully enabled to see, in this time,
wherein all sensible refreshment was withheld from my soul,
that great caution was necessary not to meddle with any forbidden fruit,
or set up any graven image in the absence of my spiritual Moses.

Sometimes, in the anguish of my heart,
I have been strengthened to cry unto Him who knows the secrets of all hearts,
"`Though you slay me, yet will I trust in you.`" Job 13:15.
In such seasons it has been shown me, I trust, in the vision of light,
that if ever I knew a full release from the present bondage,
it must be by going back to the place I had once left in peace,
even to the city of Norwich, and there visit my friends, from house to house;
though I might thereby become a "`spectacle to angels and to men.`" 1 Cor. 4:9.
This was indeed humiliating to the natural part;
yet I can honestly say that my mind was many times
brought into a state of resignation thereto,
if I might but be favoured to have a suitable companion in the work;
and after many months of close exercise, I believed this would be granted,
when the full time should come to enter upon the engagement.
Here I was permitted to leave the subject for a while, and my mind became,
in some degree, relieved from its former exercises;
so that I was enabled to engage in some little services at and about home.
This I esteemed a mercy granted by my heavenly Father,
having "`lain long among the pots,`" Psal. 68:
13, cast off and useless, and often been ready to query, "`Can these bones live?`"
Ezek.37:3.

About this time, at our summer quarterly meeting held at Woodbridge, in the sixth month,
1793, three other Friends from the women`'s meeting, and myself,
were appointed to visit the monthly meeting of Beccles,
and the preparative meetings constituting it.
A committee of men Friends having been previously nominated
to visit all the monthly meetings in the county,
some of them united with a part of our committee to Beccles,
in the eighth month following.
My friends Hannah Evens and Martha Brewster, were my female companions;
and we were favoured to get through beyond our own expectation; yet,
after my return home,
I did not feel that evidence of divine acceptance which had sometimes been my experience,
at the close of a little act of dedication.
I was however desirous of dwelling quietly in this condition,
believing that when He who knows best what is best for us, is pleased so to favour,
he can yield the desired confirmation of peace; and to be kept in a state of waiting,
is often a profitable, though to the creaturely part, a humbling dispensation.
Therefore,
when it is consistent with the great Master`'s will
to withhold the precious proof of acceptance,
for any little acts of obedience,
it is most assuredly his servants`' duty to seek after submission to him,
and ability to trust in his infinite wisdom for the food convenient;
remembering the counsel of the good Counsellor, where he says,
"`When you shall have done all those things which are commanded you, say.
We are unprofitable servants: we have done that which was our duty to do.`" Luke 17:10.

As the committee of men Friends had not, previously to our quarterly meeting,
held in the ninth month, proceeded in their visit further than with us,
it appeared most satisfactory to the women`'s meeting to continue our committee,
which some of us willingly acquiesced with,
not feeling our minds rightly liberated from the work;
and we were left at liberty to unite with the men`'s committee in all,
or any part of the remaining engagement, as way might open for it.
In the eleventh month we went through the monthly meeting of Bury:
no small addition to the weight of the prospect to me,
was the loss of the company of my beloved friend Martha Brewster,
who was at that time very unwell.
My female companions were my friends Hannah Evens and Anna Perry, and we,
as well as the men Friends, were all of us striplings;
yet I believe we were favoured to experience the mark of discipleship,
in that we had love one to another; and we were enabled to move on harmoniously together.
In the close of our visit,
we were favoured to feel a degree of that sweet quietude
of mind which is not at our command;
and therefore, I trust, it might be received as a token of divine acceptance;
and some of our hearts were filled with thankful admiration,
for the goodness and gracious condescension of our Heavenly Helper.

In the twelfth month we went through Woodbridge monthly meeting,
ended our mission peacefully,
and carried a written report of our proceedings to the next quarterly meeting,
held the 17th of the same month.
