== Chapter III.

[.chapter-subtitle--blurb]
(First month, 1794, to Tenth month, 1795.)

[.chapter-synopsis]
* Visits Norwich, etc.
* Decease of an individual at Needham
* William Bleckley`'s decease
* Burial of M. Crowley
* Cambridgeshire and Huntingdonshire
* Lincolnshire, and York Quarterly meeting

Very soon after the close of the visit to the monthly meetings, etc.,
my mind became again deeply impressed with the before-mentioned
prospect of visiting the families of Friends at Norwich;
and with such an increased weight,
that I believed the time for entering into that engagement was drawing nigh.
Ardently did I crave of my Almighty Father that he would be pleased
to guide me in every step that I took concerning it,
and to give me some undoubted evidence of the right time to move therein,
and of my right companion in the work.
And I think I did repeatedly see, when my mind, I humbly trust,
was brought in some degree under his instruction,
that I was to unite with a Friend herein,
who about this time had a certificate from York monthly meeting,
for visiting the cities of Norwich, London and Bristol.
I laid my prospect of visiting the families of Friends at Norwich,
before our monthly meeting in the beginning of the first month, 1794,
and obtained the concurrence of my friends for the same.

On third-day, the 21st of the first month, we commenced our visits in that place,
by having sittings in two families.
The next day we attended the burial of a young man at Tasburgh,
which proved a solemn meeting; and I believe, to some minds,
it was an instructive and awfully awakening time;
a day wherein the invitation of the spirit of Christ,
was renewed plenteously and preciously,
to some who had long been halting as between two opinions.

We dined at Thomas Broadbank`'s, and returned to Norwich in the afternoon,
where we had two sittings more that evening.
If ever I knew what it was to be "`baptized for the dead,`" 1 Cor. 15:29,
I think I did experience it in the course of my visit through this place.
It was a season of very close exercise.
Sometimes I was shut up in silence for several sittings together,
in great poverty of spirit; and sometimes when utterance was granted,
but little relief was obtained;
so that I was ready often to doubt whether all that I had ever felt,
concerning this engagement, was not a delusion of the great adversary of mankind.
Yes, I was fearful lest I had put my hand unbidden to the Lord`'s work, and, Uzza-like,
might fall a victim to the displeasure of an offended Creator.
But, blessed be the name of Israel`'s God, and I humbly trust my holy Leader,
when I had filled up such a portion of suffering for his pure seed`'s sake,
as he saw fit to appoint, he was pleased to say, "`It is enough,`" 2 Sam. 24:16;
and "`to proclaim liberty to the captive;
and the opening of the prison to that which was bound.`"
Isaiah 61:1
Then I was, in some families,
enabled to tell of the Lord`'s gracious dealings with my soul,
thereby endeavouring to persuade others, to enlist under the banner of the Lamb,
who is also "`the Lion of the tribe of Judah, the Root of David,`" Rev. 5:5,
who was found worthy and still is, "`to take the book, and open the seals thereof.`" Thus,
notwithstanding all the probationary seasons allotted me in this city,
the supporting and sustaining arm of never-failing power, was experienced to be near,
at times, to my humbling admiration; and, on leaving the place,
I was permitted to receive a little portion of "`the oil of joy for mourning,
and the garment of praise for the spirit of heaviness.`"
Isaiah 61:3.

At different times, while we were at Norwich, we visited three neighbouring meetings,
besides the burial before mentioned, namely, on first-day the 2nd of the second month,
Wymondham; Lammas week-day meeting on fourth-day the 5th; and Lammas monthly meeting,
held at North Walsham, on second-day the 10th of the same month.

We left Norwich on fourth-day, the 12th of the second month, and went to Tasburgh.
On fifth-day, the 13th, my brother William met us at Tasburgh,
and we all attended the monthly meeting there.
Next day, the 14th, we had meetings at Tivetshall and Diss.
On seventh-day, the 15th, my companion, my brother William Alexander and myself,
went to Beccles; and visiting the meetings of Friends at Pakefield, Leiston, Woodbridge,
and Ipswich, on our way, we arrived, on fifth-day the 20th of the second month,
at Needham, in time for the week-day meeting.
On the 21st and 22nd my companion and myself having felt a little
engagement to sit with some of the families constituting this meeting,
we proceeded, and were favoured to feel satisfaction in our movements therein;
and had to believe,
it was a time of renewed visitation of heavenly goodness to some minds,
who had been long called to work in the Lord`'s vineyard;
the vineyard of their own hearts.

After visiting a few meetings in Essex, my brother William and myself returned home,
where I was favoured to receive a peaceful release from the little field of exercise
and labour which I trust had been by divine appointment allotted me.
And, at times, I felt gladness of heart,
that I had been permitted to suffer with the pure suffering seed; and could say,
with the Psalmist, "`Gracious is the Lord and righteous; yes, our God is merciful.
The Lord preserves the simple: I was brought low, and he helped me.`"
Ps. 116:5-6.

First-day, the 30th of third month.
This was an awful day to me.
It was the final close of poor +++_______+++. He was once of our Society,
and my mind had often deeply felt on his account,
believing the Lord had long been inviting him,
to "`give diligence to make his calling and election sure,`" 2 Pet. 1:10,
before the solemn message was sent unto him of, "`You shall die, and not live.`" 2 Kings 20:1.
And thankful I was, that we had attended to the little pointing of duty,
in stepping into some families here, after our return from Norwich; believing,
to this poor man,
it was permitted to be a season of peculiar visitation from the Most High;
and it appeared to dwell with him to his end; which was about five weeks afterwards.
He was ill only two days.
His wife remarked, after his removal, that from the time of our visit,
he had appeared quite an altered man; very solid and thoughtful;
and that she had several times found him in his chamber with his bible,
a circumstance which, I think she said, she had never before observed.
When I called at his house, a little after he expired, I did believe,
from the precious quiet I was permitted to feel, that his spirit was received into rest,
which humbled my soul, and all within me, before Him,
whose "`tender mercies are over all his works.`"
Ps. 145:9. At the burial we were favoured with a solemn meeting.

In the twelfth month this year, I attended the interment of our friend William Bleckley,
of Long Stratton, in Norfolk.
It was a time of divine favour; many hearts were humbled,
and greatly lamented the church`'s loss, in the removal of one,
who was engaged to maintain the law and the testimony given to us, as a people,
to support.
I was with him several times within the last few months of his life,
at different meetings, which were seasons of solid satisfaction to my mind at the time,
and I could now review them with comfort.
Much did I desire that those who felt their loss in his removal,
and particularly his near relatives,
might be willing to follow him as he had endeavoured to follow Christ.
I believe it was a day of merciful visitation to several of his beloved offspring; who,
I trust, have since been made sensible of the truth of David`'s declaration,
where he says: "`A father of the fatherless, and a judge of the widows,
is God in his holy habitation.`"
Psal. 68:5.

1795+++.+++ In the forepart of this year, in company with two of my brothers,
I attended the burial of my beloved friend Mary Crowley.
She departed this life on the 17th of the second month;
and was interred after a meeting at Devonshire House, London, in Friends`' burial ground,
near Bunhill-Fields, on the 24th of the same month.
After my return home,
though it was not a journey which I considered in the line of religious duty;
yet it was one, I could look back upon with a peaceful calm,
and with thankfulness to the great Author of every comfort;
rejoicing that I endeavoured to pay the last tribute of affection to an endeared friend,
removed a little before me, from the conflicts of time, I humbly hope,
to the joys of eternity.

Soon after my return from the above mentioned journey, my mind became, at times,
closely brought into exercise, under the renewal of a prospect,
of visiting the meetings of Friends in the quarterly meeting of Cambridgeshire and Huntingdonshire;
accompanied with a belief, that the time was drawing near,
in which I must confess it to my friends, and request their concurrence;
and that without any knowledge of a companion.
This increased the weight of the prospect; but before I had opened the subject to anyone,
our friends Ann Tuke and Rachel Fowler, came into this county, on a religious visit;
the latter expecting to leave Ann after attending our quarterly meeting,
and that for Norfolk and Norwich, in the sixth month this year.
Finding that Ann Tuke`'s prospect was to go from these counties
directly into Cambridgeshire and Huntingdonshire,
way opened with satisfactory clearness for me to propose uniting with her.
Accordingly I laid my prospect before our monthly meeting,
and obtained the concurrence of my friends to join her through that quarterly meeting,
and elsewhere as way might open.
I met her at Bury on the 13th of the seventh month;
and accompanied her to some meetings in this county, both among Friends,
and in some places, where the inhabitants were generally invited.
In Cambridgeshire and Huntingdonshire, we visited all the meetings of Friends;
we also had many meetings in different places with people of other persuasions;
among whom we met with many well-disposed, serious, seeking minds.

After we got through that quarterly meeting, not seeing my way clear to return home,
I continued with my beloved friend through Lincolnshire;
where we visited all the meetings of Friends, and had many public meetings,
as in the other counties.
We afterwards continued together to York, where my brother William met me,
and we stayed the quarterly meeting there in the ninth month; and with Ann Tuke,
visited a few meetings in that county.
We also attended the marriage of Joshua and Elizabeth Wheeler, on our return to York;
after which my brother and myself left York again,
Henry and Ann Tuke accompanying us to Lincoln quarterly meeting; where we parted.
They returned to York, and we came home,
where we arrived on seventh-day the 10th of tenth month,
and were favoured to meet our connections well.

Thankfulness was raised in my heart, for the many mercies bestowed by a bountiful giver;
although many and various were the trials permitted to attend me,
during this separation from my outward habitation.
Some were of a nature, wherein patience and resignation were closely tried,
so that I sometimes was almost ready to conclude,
I had lost all power of ever again experiencing ability,
even to lift up my eyes to heaven,
and crave the blessing of preservation for my own soul.
Yet after a dispensation of this sort, through merciful condescension,
light did sometimes arise out of obscurity, and the darkness, before experienced,
became as the noon day; so that through all, at my return home,
I could set up my Ebenezer and acknowledge, "`Hitherto has the Lord helped me.`" 1 Sam. 7:12.
