== Chapter VI.

(Fifth month, 1798 to the Eleventh month, 1800.)

London yearly meeting.--Sundry meetings in Suffolk.--Endures a
very trying dispensation.--Visits Tivetshall monthly meeting,
etc.--Joins Elizabeth Coggeshall in visiting sundry places in Norfolk, Suffolk,
Leicestershire, Derbyshire, Nottinghamshire, and Yorkshire--Returns home.

At our monthly meeting in the fifth month, 1798,
I mentioned a prospect I had of appointing a Few public
meetings in my way to or from London yearly meeting;
in which my sister Ann united with me; and we were liberated by our friends,
to proceed therein as way might open.

In the seventh month,
I accompanied my brother Samuel in some public meetings on the eastern side of our county;
and at the close was favoured to feel much solid satisfaction.

Oh! how has my soul longed that the inhabitants of this highly-favoured land,
even many of those who have been made willing, in some good degree,
to seek the Lord for themselves, might become more and more acquainted with him,
through a willingness to centre unto the pure Spirit
placed in the secret of their own hearts.
Thus they might sensibly experience the privileges of the glorious gospel dispensation;
and know an establishment on the unchangeable and invincible rock Christ Jesus;
and then they would also know him to go before them, and to be their rearward.

1799+++.+++ On the 2nd of the first month this year, our friend Sarah Harrison, from America,
who was then on a religious visit to Europe, and who had, a few weeks before,
returned from Germany, came to my house, and was confined with me, by indisposition,
till the 9th of the fourth month following; except going to Ipswich for two days.
Great part of the time she was much tried, not only with bodily suffering,
but also with spiritual poverty: yet,
I believe there were seasons in which she experienced the Shepherd of Israel,
the great Bishop of souls, to arise for her deliverance,
whereby she was renewedly enabled to praise his holy name.

I was permitted to be her close companion in suffering, but not in rejoicing; for,
I think, from the day after she first came under my roof,
until the day I parted with her at Ipswich,
I was not once made sensible of the smallest degree of divine consolation.
Indeed, such a total cessation, as to any visible appearance of spiritual life,
I have but very seldom experienced;
though my mind was not so deeply exercised as at some other times.
Often did I fear,
lest I should dwindle into a state which might be compared to that
which the church of the Laodiceans was described to be in,
"`neither hot nor cold,`" Rev. 3:15,
and that consequently I must be in danger of receiving the same awful sentence.
But, just before we parted, which was on the 11th of the fourth month, at Ipswich,
I was permitted to know the veil,
which had long eclipsed the Sun of righteousness from my view, to be removed;
and ability was mercifully afforded to offer a tribute of
thanksgiving and praise to the great Author of all good,
and to implore his divine protection over us when far separated;
and I was favoured to return home in peace,
Sarah Harrison left Europe within a few months, having been from home, I think,
nearly seven years.

In the latter part of this year, I was exercised for some months,
under the weight of a religious prospect of visiting`'
the families of Friends in Tivetshall monthly meeting,
with some other engagements in that neighbourhood; and in the first month, 1800,
finding my mind more closely arrested with this concern,
accompanied with what I believed a clear intimation of the time to move in the same,
I ventured to mention it to my friends, in the second month,
and obtained their concurrence to proceed in my visit, as, in the pointings of truth,
way should open for it.

On the 12th of the second month, accompanied by my dear brother Samuel,
I went to Long Stratton;
the next day attended Tivetshall monthly meeting held at Tasburgh,
when I opened my prospect to Friends, and in it found much relief.
After meeting we went to Thomas Broadbank`'s,
whose house was my agreeable lodging during my stay in that meeting.
Sixth-day the 14th, my brother went to Norwich, and accompanied by Thomas Broadbank,
I began the arduous engagement in prospect.
Seventh-day, I continued the visit to families, and my brother returned from Norwich.
First-day he stayed with me,
and in the evening I had his company very acceptably in two families.
Second-day he left me, and returned home.

From this time until fifth-day the 27th,
I was closely engaged in going through the remaining families in Tasburgh meeting,
and those in Tivetshall.
First-day the 2nd of third month, I was at Tivetshall meeting.
Second and third-day, I sat in the few families constituting Diss meeting.
Fourth-day attended the week-day meeting there, and after it, contrary to my expectation,
I felt full liberty to return home, which I did that afternoon.
I was favoured with a peaceful ride home,
and felt thankful for the present unexpected release from further labour.

The next morning my mind became renewedly exercised concerning
the inhabitants of some villages where I had been,
in the course of the family visit;
with a clear prospect when and where to appoint the first meeting,
though without any uneasiness at coming home as I did.
However, I kept my feelings to myself, until the day following,
and then acquainted my near connections,
that I had a prospect of appointing a meeting at Yaxley, the next first-day evening;
which did not appear to be any surprise to them,
they having had reason to expect that some further engagements than had yet taken place,
might be required of me.
Accompanied by Thomas Broadbank, my brother Samuel, and other relatives,
on first-day afternoon, the 9th of the third month, I went to Yaxley,
where we were met by several Friends of Tivetshall monthly meeting,
and were favoured with a large and solid meeting.
After it, Thomas Broadbank, my brother Samuel, and myself, went to Diss.

Next evening we had a meeting with the inhabitants of Scole and Dicklesburg;
and after it went to the house of our kind friends John and Ann Holmes.
On third-day, a meeting at Shottisham, to my own mind, was a very relieving opportunity,
feeling divine support in a very precious manner to be near,
which was cause of thankfulness.
After it,
we went to Thomas Broadbank`'s. On fourth-day we attended Tasburgh week-day meeting,
which, though small, was a relieving and strengthening season to my mind.
I was very unexpectedly, in the latter part of the meeting,
led to address an individual present whose family I had been in,
when in that meeting before,
but did not at that time feel any openness to express anything to him;
though my mind was closely exercised on his account.
He was in this meeting, much humbled,
and I covet for him that through faithfulness to known duty,
his last days may be his best days.

That evening we had a meeting at Hempnall, where was a great variety of states;
a few solid people, and many of a very different description.
To the latter in a very remarkable manner,
the extension of divine goodness and mercy was evidently manifested,
to save them from destruction,
if there was but a willingness to accept of the means of purification.
"`Come now, and let us reason together, says the Lord,`" Isaiah 1:18,
was awfully sounded among them.

On fifth-day the 13th, we attended Tivetshall monthly meeting,
which was a season owned by the great Master of all rightly gathered assemblies.
After the last meeting, my brother Samuel and myself returned home in peace.
And I have cause to bear in remembrance my heavenly Father`'s goodness,
in supporting and carrying me through those engagements; having to acknowledge,
that although I did go out weeping, I was permitted to return with joy.
I have reason to believe my coming home before I had those public meetings was right,
in order to have my dear brother`'s company; yet, if I had seen before I got home,
with clearness, that I was to return so soon, it would, I suppose,
have felt rather trying in prospect.
To be enabled to go on day after day, just moving in the present ability afforded,
without being unprofitably anxious to see more of the work at once,
than is consistent with the great Master`'s will to unfold, I have always found,
is not more the duty than the interest of his truly dependent servants,
if I have ever known this happy state of mind;
though for lack of "`letting patience have her perfect work,`" James 1:4,
I have often times increased my trials and exercises,
I believe beyond what might have been designed for me to endure for the work`'s sake.
After such feeble efforts to promote the cause of truth, what a mercy it is,
to be favoured with any sensible evidence of the
approbation of the great Minister of ministers!
Yet I humbly trust that such was my consoling experience in the close of this visit;
and under the humbling influence thereof, I was enabled, renewedly to acknowledge,
"`Hitherto has the Lord helped me.`" 1 Sam. 7:12.

In the eighth month this year, Elizabeth Coggeshall, from Newport, Rhode Island,
in the course of her religious visit to Europe, came to Needham,
accompanied by Abigail Pimm of London, who left her here and returned home.
When I first heard of their arrival,
and that A. Pimm was likely to leave E. Coggeshall immediately,
it very forcibly impressed my mind,
that it would be right for me to unite with the latter,
in some part of her future prospects; and before I saw her, it was I apprehended,
pretty clearly manifested to my mind, that I should join her in Norfolk,
and continue with her until she reached Yorkshire.
This I kept to myself wholly, for a few days, while she remained in this neighbourhood;
and before she left it,
I found my sister Ann had a prospect of accompanying Elizabeth for the present:
but upon our opening our views to each other, her`'s appeared to close where mine began.

In the ninth month,
I informed my friends of my prospect of joining our friend E. Coggeshall for a while,
and received their concurrence.
On seventh-day, the sixth of this month, accompanied by my brother Samuel,
I went to Tasburgh.
Next morning, at Wymondham, we met E. Coggeshall and my sister Ann;
also my brother William, who went to meet his wife a few days before.
After attending the meeting there, we all went to one held at Mattishall in the evening.

After this meeting, my brother William and his wife went towards home;
and my brother Samuel, E. Coggeshall, and myself,
accompanied by our friend Thomas Broadbank, went on to Dereham.
On second-day my brother left us, and returned home, and Thomas, Elizabeth, and myself,
went to Holt, where we intended having a meeting with Friends that evening.

The Friend`'s house where we were to take up our quarters, being out of the town,
and a contrary way to that which we entered, we were obliged to ride quite through it;
and my mind became so much interested on account of the inhabitants at large,
that it did not appear right to conceal my prospect from my dear companion,
and she uniting with it, public invitation was given, and we had a satisfactory meeting,
in which we were favoured with the overshadowing wing of divine mercy;
and under the influence thereof,
ability was afforded to minister to various states and conditions present.
The greatest part of the public labour devolved upon Elizabeth:
but I felt my mind in a peculiar manner engaged for the welfare of some individual, who,
like the prodigal son, had "`wasted his substance with riotous living;`" Luke 15:13;
believing our heavenly Father was still graciously
disposed to receive such a one in mercy,
if there were a willingness to return unto him.
At the time I was speaking, I had not any knowledge who it was I was addressing;
but after meeting, I thought I could have lain my hand on the head of an individual,
and have said, "`You are the man;`" 2 Sam. 12:7;
but as it did not appear a divine requisition so to do,
I believed it best to leave him to the unflattering witness in his own mind.

On third-day, the 9th, we were at Wells monthly meeting; fourth-day,
Swaffham weekday meeting; fifth-day, Lynn monthly meeting.
Sixth-day we had an appointed meeting at Wareham in the morning;
and one in the evening at Brandon; and on seventh-day,
an appointed meeting at Mildenhall.
First-day, 14th, we attended Thetford meeting; and afterwards went to Bury.
On second and third-day, the quarterly meeting was held there.

After our quarterly meeting, my dear E. Coggeshall,
not seeing her way from Bury into Leicestershire,
I mentioned a place we passed through in Norfolk,
which had dwelt pretty much with me during my stay at Bury,
believing it would be right for me to have a meeting with the inhabitants there at Stoke.
This acknowledgment from me, soon cleared her way; and we made it known to our friends,
and had a meeting appointed at that place on fourth-day evening, the 17th,
which proved a memorable opportunity.
I believe it was a time of precious visitation to
many of the inhabitants of that place and neighbourhood.
And though it was somewhat more than usually trying to me to propose this meeting,
considering myself set out with one, who, I expected,
would generally have to lead the way; yet, after it was over,
the reward I was permitted to feel in my own mind,
was a very full compensation for what I had passed through before it:
indeed I think I have but seldom felt such an uninterrupted flow of peace,
as was my happy experience through that evening.

Fifth-day, 18th. We went this morning to Wareham, with my brother Samuel,
who had kindly accompanied us the preceding day from Bury.
After breakfast,
we had a precious season of solid retirement in the Friend`'s family there;
and after it took leave of them and my dear brother, he returning home from this place.
We proceeded towards Leicester; and on sixth-day evening, had a meeting at Oakham,
in Rutlandshire.
First-day, 21st, we were at Leicester, to good satisfaction;
my mind was nearly bound to some exercised minds in that place.
Second-day, we had a meeting at Hinkley, and afterwards returned to Leicester.

On third-day evening, the select quarterly meeting was held there;
and next day the quarterly meeting.
A mournful time it was to me; occasioned, I believe,
by my withholding more than was fitting, which tended to poverty, and distress of mind;
yet I think it was more from a preference I felt for others,
whose public labour I esteemed before my own,
than from any unwillingness to offer the food given me to hand,
though it might have appeared but as the barley loaf;
for that with a little of the divine blessing,
doubtless would have proved sufficient to have fed those, for whom it might be designed;
which was my painful reflection when too late.

After a time of sore conflict before we left the family there,
where we had been very kindly entertained several days,
a little ability was mercifully afforded me, to intercede for them and ourselves,
that we might all be enabled so to pass our time of sojourning here,
as at last to know an admittance where sorrow is no more.
And matchless goodness was pleased, in the close,
to convey intelligibly to my secret feeling,
"`It is enough:`" and I left Leicester in peace.

On fifth-day we had a meeting at Loughborough;
and in the afternoon went to Castle Donington, to the house of our valuable,
ancient friends George and Ruth Fallows, where we enjoyed a peaceful evening with them,
and were much comforted and encouraged by dear Ruth`'s instructive company and conversation.
On sixth-day we had a meeting at Castle Donington,
in which Elizabeth had some public labour among a people,
many of whom appeared to be too much strangers to
the precious privileges of these gospel days,
although most of them were professing to be worshippers
of the great object of adoration in spirit and in truth;
so that it proved an exercising season;
but a little opportunity of solid retirement in the family after dinner,
enabled us to leave the place with relieved minds;
and that evening we had a meeting at Derby.

On first-day the 28th, we were at Nottingham meeting in the morning, where,
after sitting a while in close exercise,
a little ability was afforded me to cast off my burden.
I was permitted to feel relief when I took my seat again,
and my dear E. Coggeshall had a very lively testimony afterwards, much to my comfort;
and as far as relates to ourselves,
I believe we were both favoured to partake of a portion
of peace at the close of the meeting;
yet, I had much to fear that the word preached, to some states in particular,
would prove altogether unavailing.
Yet, oh! what a mercy,
amidst the many discouraging circumstances which we are liable to experience,
when passing along from place to place in gospel bonds,
to know that the reward of our labour is not confined
to the reception our mission meets with from man,
but is proportioned to our obedience to Him, who sees and knows the hearts of all men.

At Nottingham, Joseph Marriage, who had accompanied us from Bury, left us,
and returned home.
That evening we had a meeting at Mansfield.
On second-day morning we went to Chesterfield,
to the house of my much esteemed friend Joseph Storrs,
and in the afternoon we had a meeting there; which to me was a very gloomy season;
but dear E. Coggeshall had acceptable service both in testimony and supplication.

On third-day we had a meeting at Furnace,
where my mind was pretty closely exercised for two
individuals who came into the meeting rather late,
and had but little appearance of being members of our Society.
Upon their entering into the meeting-house,
I thought I felt a flow of gospel solicitude raised in my mind on their account;
particularly did I feel for the female,
and believe it was a time of humbling instruction to her mind:
I wish it may prove of lasting advantage to her.

On fourth-day we had a meeting at Breach,
which was measurably owned by the great Shepherd of Israel.
On fifth-day, we travelled through a mountainous country; and in the course of this day,
as we passed through some small villages,
my mind was so attracted towards the inhabitants of them, that I believe,
had we been free from previous engagements by other meetings being appointed for us,
I should have felt best satisfied to have acknowledged it to my dear companion;
but as that was the case, I kept my feelings to myself.
In this instance I believe it was needful for meetings to be fixed a little beforehand,
on account of the particular situation of some places thereabouts; but, in general,
I have found, in any services of this sort, in which I have been engaged,
that it was safest, and indeed was my incumbent duty, as much as possible,
to live as it were one day at once.

On sixth-day we had a meeting at Mony Ash, and after it returned to Chesterfield.
On seventh-day morning,
before we left the hospitable roof of our kind friends Joseph and Mary Storrs,
we were permitted to experience a little season of retirement, wherein, I trust,
our minds were humbled together before Him, whose tender mercies are over all his works.
Joseph Storrs went with us to a meeting at Retford that evening.
On first-day, the 5th of the tenth month, we went to Blyth in the morning;
and in the evening had a meeting at Barnby Moor,
a small village we had passed through in the morning.
It was a considerable trial to me to give up to appoint this meeting,
finding some friends were apprehensive it would not be likely to prove satisfactory.
One objection appeared to be the smallness of the place,
though I wished invitation to be given beyond the village,
if a situation large enough could be procured to admit of extending it further;
but what weighed more with me than any other obstacle,
was the difficulty which our kind friend Joseph Storrs felt about its accomplishment;
yet, unless he could have said he believed it best for us to give up the meeting,
I did not feel it safe to do so, without making some attempt to have one,
my dear E. Coggeshall being fully resigned to it,
though she felt nothing towards it herself.
We had, in the end, to acknowledge the goodness and mercy of our heavenly Father, who,
blessed be his great and glorious name,
does not send his children and servants a warfare at their own charge,
but is mercifully pleased,
sometimes when they appear to be reduced to the greatest extremity,
to prove himself to be strength in their weakness.
Our dear friend J. Storrs, before he parted with us this evening,
told me he was glad he had been at that meeting; which acknowledgment,
added to the peaceful serenity before felt,
caused the rest of the evening to be a season of humbling gladness.

On second and third-day, we travelled to York; but before we got there,
E+++.+++ Coggeshall began to be apprehensive it would be best for us to attend
a monthly meeting to be held at Warnsworth the fifth-day following;
and after we got to York, the weight increasing, we concluded to return.
After the meeting at York on fourth-day, accompanied by Henry Tuke,
we went part of the way;
and on fifth-day morning we got in seasonable time to the meeting at Warnsworth,
which was a low time with me; but dear E. C. had acceptable service,
in the meeting for worship.
When I found that Elizabeth had a prospect of attending this monthly meeting,
as I began now to feel very near the end of my present mission,
I thought it probable some friend among them might find, at least,
a religious liberty to join her for a while; and, therefore, in the women`'s meeting,
I mentioned how I was circumstanced,
and wished Friends present to endeavour to feel whether
the lot did not fall among some of them,
to unite with our beloved friend; but no one appearing to see it their place so to do,
I returned with her to York.

We were at York on first-day the 12th; and I was able to rejoice,
in ability being afforded to my dear friend to labour in her great Master`'s cause,
though it was a very low time with me.
As no companion offered, I did not feel satisfied to leave her,
and therefore I concluded to set out with her again on second-day morning,
in order to take some meetings in that county;
expecting we should return the following first-day.

We had meetings at Pickering and Malton; were at Pickering monthly meeting,
and afterwards had meetings at Hutton in the Hole, Helmsley, Bilsdale, and Kirby,
and so returned to York.
We left it again and went to Thirsk, Borrowby, and Masham.
At this latter place our friend Mary Tate, of Cottingwith, near York, met us,
for the purpose of uniting with Elizabeth, and that day, the 24th of the tenth month,
I parted with them, after a religious opportunity to be remembered with gratitude.
My soul was poured forth in supplication to the Father of Mercies,
for the blessing of preservation, through the remaining part of our pilgrimage here,
whether we should ever be permitted to meet again in this mutable state or not;
that so we might be prepared to join the just of all generations,
whenever the midnight cry should be heard, of, "`Behold, the bridegroom comes;
go out to meet him.`" Matt. 25:6.
My beloved friend and her new companion,
went to a meeting appointed for them that evening at Leyburn, and I returned to Thirsk;
and on the way, by the food received before we separated, was sweetly sustained,
to the gladdening of my heart.
Indeed for some days after, my mind was preserved in such a state of tranquillity,
as was cause of thankfulness.

On sixth-day I returned to York; where I stayed until fifth-day the 30th,
and left in company with several Friends.
Eleventh month 2nd, first-day, we attended Friends`' meeting at Derby,
where we were joined by J. and E. Hoyland, and with them we travelled to Hitchin,
which place we reached on fourth-day evening,
the 5th. Here I was met by my brother Dykes, who accompanied me home on third-day,
the 11th of the eleventh month.

After parting with my beloved companion E. Coggeshall,
I thought it a privilege to have the company of my much-valued friends before mentioned:
and that my dear brother was disposed to meet me when I parted with them.
After I got home,
though I left it this time more from an apprehension
of duty to unite in sympathy with a beloved friend,
than from a prospect of any religious engagement on my own account, I felt peace.
And I humbly trust there were seasons experienced,
wherein my dear friend and myself could feelingly acknowledge,
we were bound together in gospel unity;
harmoniously labouring for the advancement of the most noble cause,
which can be advocated on earth.
May it be our happy employ to celebrate it in a joyful eternity,
through an unreserved dedication of heart during our stay here, to the whole will of Him,
who has a right to dispose of us as he sees fit.
