== Chapter VII.

(Twelfth month, 1800, to the Ninth month, 1802.)

Concern for the youth,
etc.--Huntingdonshire and Cambridgeshire.--Religious prospects.--Visit to Surrey, Sussex,
and Hampshire quarterly meetings,
etc.--Returns home.--Visits sundry villages in her own county.--Burial
of Isaac Brightwen.--Decease of +++_______+++.

Previously to our quarterly meeting, held here in the twelfth month this year,
and during its sittings,
my mind was dipped into a state of mourning on account of some of its members, who,
I was ready to fear, through unwatchfulness, had of late declined,
rather than advanced in the way which leads to enduring felicity.
Many of the youth appeared on the wing, soaring above the pure simplicity of the truth;
and having the company of several of these at my own house,
I apprehended I felt a necessity laid upon me to
intercede with the Father of mercies on their behalf.
I was engaged to desire that they, with many more,
might be prevailed upon to choose him for their portion,
and be willing to follow him in the path of unreserved dedication,
which yields more substantial comfort here, than any sublunary enjoyment can possibly do;
and affords a well-grounded hope of an admittance hereafter into unmixed happiness.
I think I have not often felt more solid satisfaction
result from an engagement of this sort,
than I was permitted to feel that evening.

1801+++.+++ In the forepart of this year I was often closely tried
concerning an individual in the station of an elder,
for whom I had long entertained a sincere regard;
but who now seemed in danger of making shipwreck of faith.
At our quarterly meeting in the third month, my painful apprehensions increased, so that,
in the bitterness of my soul, I was almost ready to utter the mournful language,
"`Who shall stand?`"
Ps. 130:3;
when a ray of holy confidence in the never failing arm of divine sufficiency,
was mercifully vouchsafed, after this season of deep discouragement.
It proved the eve of a precious day in the quarterly meeting at large,
wherein we were graciously owned by the great Father of his people,
and some of us had cause humbly to acknowledge his fatherly dealings with us,
and that to Him, with his beloved Son, our blessed Saviour,
belong all thanksgiving and praise.

In the sixth month,
my brother Samuel and myself were a few days in Huntingdonshire and Cambridgeshire,
with a friend who was then in these parts on a religious visit,
and was going into Scotland.
The time we were together was short, but feeling the uniting bond of gospel fellowship,
I think we were permitted to be as a threefold cord.

We parted with this friend, after a meeting at Huntingdon, in which I trust, I may say,
truth gave us the victory.
Though it was but a small gathering,
there appeared to be many different states among them,
a few I believe humble travellers for the prosperity of the pure cause.
May they be strengthened in every good word and work, by the mighty power of Him,
who can still enable "`a little one to become a thousand,
and a small one a strong nation.`" Isaiah 9:22.
After meeting we were favoured with
a baptizing time in Hannah Evens`' family;
and a little season of retirement in Phebe Fuller`'s, before we separated.
Brother Samuel and myself reached home the next day, the 24th of sixth month.
For some days after, my mind was permitted to experience an uninterrupted tranquillity,
which I desire to acknowledge with humble thankfulness to Him,
with whom are all the blessings both of time and eternity.
It afforded a morsel of nourishment for many days,
during a season of close exercise and trial;
which it was my allotment to experience very soon after this time.

First-day, 23rd of eighth month, 1801.
A weighty religious prospect, of which I have had a distant view, at times,
for several years, has been the close attendant of my mind for many weeks past,
and occasioned me much deep, though hidden, exercise;
not feeling liberty to disclose it to anyone; though I have sometimes of late,
been almost ready to apprehend I must make it public at our next monthly meeting.
While I was awfully contemplating the subject in meeting this morning,
with my mind entirely resigned to do so,
if permitted to see clearly that the time for moving therein was come;
I heard a voice distinctly, to my spiritual faculties, declare,
"`A ram caught in a thicket;`" Gen. 22:13, accompanied with an evidence that,
at least, for the present, the will was accepted for the deed.

Immediately after it, another prospect opened to my view with great clearness, namely,
to attend the ensuing quarterly meetings for Surrey, Sussex, and Hampshire;
and to visit some particular meetings and places in those counties,
which appeared as a sacrifice that would be accepted,
and therefore might be compared to "`The ram caught in the thicket.`"

First-day, 30th of the eighth month.
This prospect has continued with such unclouded clearness, that.
I dare not doubt its being right to move therein,
if my friends are free to set me at liberty.
And whether the more important concern, because more extensive,
ever should be opened again, I desire to leave with Him,
whose wisdom and knowledge cannot be searched;
for assuredly his ways are past finding out.

At our monthly meeting, in the ninth month,
I laid before my friends the above religious prospect,
and obtained their concurrence to move therein as best wisdom might direct.
My brother Samuel was, at this time, under an appointment from the yearly meeting,
to visit, with several others Friends, the quarterly meetings of Sussex and Surrey.
His daughter Lucy feeling an inclination to accompany
her father to the above quarterly meetings,
we all left home together on the 14th of this month, and went to Bury,
in order to attend our own quarterly meeting to be held there;
intending to proceed on our journey after it.

In our way to London, we had a meeting with the inhabitants of Boxford,
to pretty good satisfaction.
On seventh-day evening, the 19th, we got to Ryegate in Surrey,
where my brother met his companions.
The next day we attended the two meetings held there, and in the evening,
the quarterly meeting of ministers and elders for that county; and on second-day,
the quarterly meeting.
We likewise attended the quarterly meeting for Sussex, and that for Hampshire.

After this last quarterly meeting,
a part of the yearly meeting`'s committee went directly to London.
But my brother Samuel and some others, accompanied me a day or two longer.
On seventh-day evening we had a meeting with the
inhabitants of Issington and another village,
in the neighbourhood of Alton.
On first-day, the 27th, we were at Godalming, attended both the meetings,
and had a relieving opportunity in a Friend`'s family in the evening.
On second-day morning, my dear brother and the rest of the yearly meeting`'s committee,
with his daughter, left me, and went to London,
in order to attend the quarterly meeting there, that being a part of their commission.

As I did not feel anything to draw me there, I was most easy to stop in Surrey;
and on third-day, I attended Guildford monthly meeting.
Fourth-day morning I went to Esher, to the week-day meeting;
where I had the satisfaction of meeting my brother Samuel, who had returned from London,
and he continued with me through the journey, to my comfort and help.
On fifth-day we attended Kingston week-day meeting, and after it returned to Esher.
In the evening we were at a meeting at the meeting-house there,
to which the inhabitants of a neighbouring village were invited,
no situation nearer appearing so suitable to hold the meeting in with them.
If one could have been obtained at the place, it would, probably,
have proved more relieving to us; yet, I trust, we had cause to acknowledge,
that divine assistance was mercifully afforded to
minister to several different states among them.
On sixth-day we had a meeting at Dorking with the Friends of that place and Capel;
and in the evening had a public meeting at Capel.

Tenth month 2nd, first-day.
We attended Ryegate meeting in the morning, and Ifield in the afternoon.
In these two meetings, and in a sitting in a Friend`'s family this day,
we had cause to acknowledge the continued support graciously extended,
from the bountiful dispenser of his own precious gifts; which,
we are often times permitted to know, are in no way at our own command;
and therefore they ought to be accepted with gratitude and thankfulness,
when they are dispensed to us.

On second-day we had a meeting at Horsham:
third-day attended a monthly meeting at Chichester;
and in the evening had sittings in two Friends`' families.
Fourth-day we sat with the rest of the families there.
Fifth-day attended Arundel week-day meeting.
Sixth-day, we had a large meeting with the inhabitants of Petworth,
which was an exercising season,
but I think ended to a good degree of relief to our tried minds.
On seventh-day, we went to Brighton, and on our way had sittings in two families.
On first-day, the 11th, we attended the meetings at Brighton.
In the forenoon, I sat under a silent exercise; and in the afternoon,
for a considerable time, the same situation was my allotment;
yet I felt much for several states among them;
and at length was permitted to see the way open for a little casting off my burden,
in testimony to them, and intercession with the Father of Mercies on their behalf.

On second-day we went to Lewes; and on third-day we had a meeting there.
After it, I could not see, for some hours,
which way we should be likely to move from there; but,
after a relieving opportunity in a Friend`'s family in the evening,
it clearly opened to leave these counties,
after having a meeting with the inhabitants of Bletchingly.
On fourth-day morning we returned to Brighton,
where we parted with our dear friend Sarah Hack,
who had very acceptably accompanied us from Chichester.
That afternoon we went to Ryegate.
Fifth-day evening we had a satisfactory meeting at Bletchingly, and after it,
went home with our kind friend Thomas Dann of Nutfield
at whose house we rested the next day,
expecting to go from there to Rochester; in order to attend a quarterly meeting there,
to which my beloved brother felt bound, and I felt full liberty to accompany him.

On seventh-day, in company with Thomas Dann and his daughter, we went to Rochester;
and were at a meeting there, on first-day, the 18th. On second-day,
we attended the quarterly meeting.
Third-day went to London, to our kind friends John and Tabitha Bevans.
Fourth-day morning we left them, after a solid opportunity in their family,
and went to Grace-Church-street week-day meeting, where my dear brother had a lively,
and to some faithfully exercised minds, an encouraging testimony.
In the afternoon we went to Upton.
On fifth-day we went to Tottenham, and on sixth-day proceeded homewards;
and reached Ipswich on seventh-day evening.

On first-day, tenth month 25th, we attended the meetings there; and in the evening,
had a humbling season of awful retirement in our friend Isaac Liversedge`'s chamber,
who was then very ill, of an indisposition from which he did not recover,
though he lived several weeks longer.
We returned home after it, well satisfied that we went round by Ipswich to visit him,
that being our principal motive for going there at that time.
After my return home, I had renewedly to acknowledge the goodness and mercy of Him,
who is still graciously pleased to reward the sincere,
though feeble endeavours of his little ones, with a portion of that peace,
which can come only from his boundless treasury, and therefore, I humbly trust,
may be received as a mark of divine acceptance;
and is a jewel worth toiling long to obtain.

In this little journey I experienced many different dispensations.
Sometimes, when I believed it to be my duty to appoint meetings,
weakness has been so much the covering of my spirit, in getting through them,
that I was often led to fear lest I should have run,
without being sent by him who alone can qualify for his own service; yet at other times,
I have humbly and thankfully to acknowledge,
I never was more sensible of divine support and qualification
to perform what appeared to be required of me,
both among Friends and others.

Under a humbling consideration of my heavenly Father`'s goodness, my soul was,
after my return home, many times bowed in reverence before him;
craving his protecting care, both in heights and in depths;
that under every dispensation of his unerring Providence, there may be ability to say,
"`Your will be done.`" Matt. 26:42.

Very soon after our return home,
we had an account of the departure of dear Mary Ann Smith,
who closed this life the day after we left Tottenham.
Though there appeared but little,
if any probability of her recovery when we parted with the family;
yet it was unexpected to us, so quickly to receive the intelligence of her awful change;
but as I believe her spirit was happily prepared for it, it is a great mercy to her,
that Infinite Wisdom has been pleased to cut the work short in righteousness;
and to admit her to a full enjoyment of that precious communion with himself,
the foretaste of which, I verily believe, she accounted her choicest blessing,
while here.

1802+++.+++ I had not been long at home,
after my return from the foregoing visit to the counties of Surrey and Sussex,
etc. before another religious exercise revived in my mind,
which I had felt at times for several years; namely,
to hold some meetings in small villages on the western side of this county.
Very early in this year, the time for moving therein appeared clearly to open,
and I found my dear friends John Kirkham and Martha Brewster, had similar prospects;
and that the former had felt his mind particularly
impressed to make known to me his concern,
without any previous information of my having any such prospect.
I informed him and my friend Martha Brewster of the time I had in view; which,
after solid consideration, they felt easy with,
and we applied to our different monthly meetings in the fourth month,
and obtained the concurrence of our Friends respectively to unite,
and proceed agreeably to our prospects laid before them.

We met at Bury, on seventh-day, the 10th of the fourth month;
and on first-day attended the morning meeting there.
In the evening we had a meeting with the inhabitants of Horringsheath,
a village in the neighbourhood of Bury.
From this time, until fourth-day, the 21st, we were in a similar manner engaged,
holding meetings within a short distance of that place.
And in most, if not at all of them,
among a people who were very much strangers to us as a religious Society.
Many of them appeared also much strangers to all true religion,
and to that divine influence which only can quicken the soul,
to a lively sense of the goodness and mercy of our great and gracious Creator;
and enable us to perform acceptable worship unto "`Him, who is a spirit,
and must be worshipped in spirit and in truth.`" John 4:23.
Yet, in some places, we met with a few seeking minds, to our comfort;
and among them, at times, we were enabled to renew our strength in the Lord,
who from day to day was pleased to give us to know
that he was sufficient for his own work;
though when with a people who were so much unacquainted with his spiritual assistance,
it was sometimes humiliating labour.
However, some of these seasons were succeeded by a degree of that solid satisfaction,
which compensated for the suffering of the day.
Where the great Master is not admitted to reign, his faithful servants cannot but suffer;
and they ought to esteem it a favour to be found worthy to abide with him,
even in tribulation.

The last mentioned evening, the fourth-day 21st, we had a meeting at Bottesdale,
with the inhabitants of that place;
and after it set off with several Friends who accompanied us there,
intending to return to Badwell-Ash.
We had not got out of the town of Bottesdale, before we experienced a very close trial,
occasioned by one of our Friends receiving a very alarming hurt on his head,
by a fall from his horse, which ran away with him immediately after he had mounted.
As soon as we could get him taken back to the inn which we had just left,
we had a surgeon`'s assistance,
who appeared to be a man of good judgement in his profession,
which was an alleviation to our tried minds.
After staying with him till all was done for him
that we were able to do under his then circumstances,
most of us proceeded, as we had before intended, to Badwell-Ash,
leaving two Friends with him for the rest of the night.

On fifth-day morning, Martha and myself felt most easy to go back to Bottesdale,
to see the Friend who had been hurt,
whom we found quite as well as we could reasonably expect,
which was cause of heartfelt gratitude to the great Preserver of his people.
We stayed with him until that afternoon, when his wife, who had been sent for,
came to him; and she accompanied him home the next day.
We had one meeting more before we returned to Bury, and got back there on seventh-day,
the 24th.

Though our absence was but for a few days,
we had experienced some deeply proving seasons, wherein our faith had been closely tried:
yet we had abundant cause to acknowledge,
that our minds had been graciously favoured with divine support in the time of need,
to our humbling admiration.

The next day we attended the morning meeting at Bury;
and in the evening had a large number of the inhabitants.
Invitation was particularly given to the lower class of the people,
and it proved a relieving opportunity to our minds;
which we esteemed a gracious mark of divine condescension,
after some deeply trying baptisms.
After this meeting was over, we all felt the weight of our present mission so lightened,
as to believe a release was near approaching.
After visiting a few Friends in their families on second-day,
the way was clear for our coming to Needham on third-day, the 27th of fourth month;
and that evening my beloved companions had a public meeting here,
invitation having been given to the inhabitants of Barking, at John Kirkham`'s request.

On fourth-day, after a solid opportunity together, with our very kind helpers,
John Marriage, jun.
and John Perry, we parted; the former accompanying John Kirkham home.
At the time of parting, my mind was permitted to feel a degree of peaceful quiet; but,
I think, I have seldom, if ever, experienced the same stripped,
tried situation so soon after any engagement of this sort, as was my allotment,
with but little exception.
Although I could not but believe we were right in parting when we did,
yet an apprehension was prevalent that it remained an unfinished work.
Earnest have been my desires,
that on whomsoever the lot may fall to be again engaged in it,
we may be enabled to keep our eye single unto the Shepherd of Israel, who,
I humbly trust, did put us forth, go before us,
and granted a present re lease from that field of labour;
then he may be pleased to unfold to us the further discovery of his holy will,
and enable us to be resigned thereunto.

On first-day, the 2nd of fifth month, I accompanied my brother Samuel to Diss,
to see our friend Isaac Brightwen, who, we had been informed,
appeared to be very near his final close; and when we got there,
we found he was not sensible,
and in such a situation as to leave no reason to expect his surviving many hours.
We attended a meeting there, which was a solid opportunity,
and after it returned to the house;
and his wife requesting our going into his chamber to them, we did so,
and sat until we saw the awful conflict finished;
when we were permitted to feel a precious covering,
accompanied with a belief that the deceased had quitted mortality,
for a glorious immortality.
Before we left the house,
we were favoured with a humbling uniting season with his widow and children.
The following first-day, the 9th, we attended the burial,
which was a memorable meeting to me, and I trust to several others who were present:
yet I fear such opportunities are too frequently soon forgotten.

Ninth month 30th, fifth-day.
The remains of +++_______+++ were interred in Friends`' burial ground here.
He was one over whom I had many times lamented,
from a firm persuasion that if he had been faithful
to the pure manifestations of truth in his own mind,
he would have been dignified thereby, and have been made useful unto others.
But instead hereof, it is to be feared,
for lack of keeping watchful and faithful in the day of small things,
to the discoveries of the divine will concerning him,
the enemy of all righteousness prevailed so far over his once enlightened mind,
as to induce him to let fall various testimonies to the pure principle of truth, which,
I verily believe, in his youthful days, were precious in his view.
Yet I am willing to believe, that through much tribulation he has obtained mercy,
and is admitted into holy rest.
In the last few days of his life, I repeatedly sat by his bed side,
and was sometimes favoured to feel a consoling belief that this would be his happy experience.
