== Chapter VIII.

[.chapter-subtitle--blurb]
(Twelfth month 1802, to the Seventh month 1804.)

[.chapter-synopsis]
* A season of withdrawing, and trial
* Hitchin
* Visit to Friends`' families, etc. in Suffolk
* London yearly meeting
* Her sister Ann`'s visit to America
* Reflections
* Renewal of a religious prospect alluded to, in 1801
* Cast before the monthly meeting
* Remark on her feelings upon such occasions

The latter end of this year, and most of the first month 1803, I was at Ipswich,
with my dear sister Hannah.
Though I was well satisfied therewith,
believing it to be my duty to do what I could to alleviate
a time of trial which she was permitted to experience;
yet, as to myself, it was a season of peculiar withdrawing of all substantial comfort.
Sometimes I could not but secretly mourn my destitute state of mind;
and had there not been a little cheering ray of holy confidence, mercifully vouchsafed,
in that All-sufficient Power, who is still able to "`open,`" at his pleasure,
"`rivers in high places, and fountains in the midst of the valleys;
to make the wilderness a pool of water,
and the dry land springs of water;`" Isa. 41:18, I think,
it seemed almost as if I must have sunk into irrecoverable sadness.
But, blessed be the name of Israel`'s God,
he was pleased to sustain through this long winter season; and at times,
to afford a grain of living faith, that when his wisdom saw it was enough,
the cloud should be removed from the tabernacle.
I was sometimes ready to conclude,
my present suffering was intended as a preparatory dispensation,
for an arduous and important engagement,
which towards the latter part of the time revived and spread in my mind;
though not with sufficient clearness to satisfy me,
the full time was come for opening it to my friends.

In the latter end of this month,
I accompanied my brother and sister William and Ann
Alexander to Hitchin, where,
on fifth-day the 27th, we attended the interment of dear Joshua Wheeler.
It was a solid meeting, and several lively testimonies were delivered therein;
as there were likewise in an opportunity in his family in the evening.
Though, as to myself, I experienced, through the day, much poverty of spirit,
yet I was well satisfied in being there,
and glad to be witness to the gracious support mercifully vouchsafed to dear Elizabeth,
who was strengthened to bear testimony in the evening,
to the goodness and sufficiency of that divine power which had
supported her under the present deeply afflictive dispensation.

After my return home, I went again to Ipswich,
and stayed about ten days longer with my sister Hannah,
During that time I felt more closely the weighty
prospect which had revived before I left her.
After I got home, it so much increased in weight,
as to induce me to believe it was right for me to open to my friends, in the third month,
a prospect I had of visiting the families of Friends throughout our quarterly meeting;
and also of holding public meetings; particularly on the western side of the county,
in some villages which were left unvisited when I
was joined by John Kirkham and Martha Brewster;
and I obtained the concurrence of Friends to proceed therein.

To give up thus far without any knowledge of a companion,
was a sacrifice which cost me many hours of close exercise of mind,
and many fears for the honour of the pure cause I was about to espouse.
To be so engaged among several who were not strangers to me,
increased the arduousness of the work in my view;
believing it would be in a peculiar manner needful to stand resigned,
to renewed baptisms, in the course of such an engagement;
in order to experience all inferior judgment removed, and to feel an entire reliance,
from hour to hour, on the guidance of unerring Wisdom.

My mind for a short season was permitted to receive consolation,
from an acknowledgment of my beloved brother Samuel`'s to the monthly meeting,
that he felt most easy to inform his friends, he believed, if no other companion offered,
he should feel bound to accompany me through some part of the visit.
He had their full concurrence so to do,
and in the course of our religious engagements together, I had good cause to believe,
that his willingness to sympathize with me,
and as far as was consistent with the great Master`'s will,
to become a fellow-labourer in the arduous work, was not all he was called to,
but that he was separated for a similar work,
within the compass of our own monthly meeting.

We left home on seventh-day, the 19th of the third month,
and went that evening to Woodbridge, and the next morning to Leiston,
in time for meeting.
In the afternoon and evening we had four sittings in the families there.
On second and third-days we sat with the rest of that meeting in their families.
Fourth-day morning, we began a visit to the families at Woodbridge;
and finished the next evening.
On sixth-day morning, we had a meeting with Friends there;
and in the afternoon were favoured to leave them in peace.

In the evening we had three sittings at Ipswich,
and there we were in a similar manner engaged, until fourth-day evening,
the 30th of this month.
During our visit in that place, I underwent the deepest baptisms, I ever experienced.
For several days after we got there, it seemed as though every day they grew heavier,
so that sometimes I was almost ready to feel dismayed, lest I had begun a work,
which I should not be able to accomplish.
But, to the praise of our Holy Head and High Priest, I was favoured to witness, that,
sufficient for the day, was the strength he was pleased in mercy to dispense.
That evening, after the close of the visit, and through the greatest part of the night,
I was favoured to partake more largely of the foretaste of enduring felicity,
than ever I had done before.
It was a night which I desire may ever remain in my remembrance,
with reverent thankfulness to the blessed Author of all good.
I thought to feel what I then felt, uninterruptedly, would, without augmentation,
constitute a joyful eternity.

The next day, at a meeting with Friends there,
I was renewedly plunged into close exercise,
though not without some ability to cast off my burden, by ministering to them,
and interceding with the Father of mercies for them and ourselves.
But I did not feel a full release from Ipswich,
without submitting to invite all my brother Dykes`' workmen,
and such of their families as inclined to attend, to come together that evening;
and it proved a solid opportunity.
After it was over, I was favoured to experience a renewal of the precious peace,
which had been my allotment the preceding evening.

On sixth-day morning, the 1st of the fourth month,
after sitting with a young woman who attends meeting, but is not a member of our Society,
we came home; and a happy day it was to me, feeling the incomes of enriching peace.

On first-day the 3rd, I attended Mendlesham meeting,
and afterwards sat with the few Friends in their different families.
On third-day the 5th, I was at our monthly meeting held at Ipswich.
Fourth-day, accompanied by my brother Samuel,
I visited the families in our own particular meeting:
but my mind was under too heavy a load of discouragement, in looking towards the future,
to get relievingly through the present engagement.
However,
I have reason to apprehend that the close of this day might have proved more satisfactory,
had I attended more to the great Master`'s injunction of,
"`Take therefore no thought for the morrow;
for the morrow shall take thought for the things of itself.`" Matt. 6:34.
This I was favoured to see verified the next day, the 7th of fourth month.

In the morning I took my leave of my beloved brother Samuel,
who expected to set out in a few days for the half year`'s meeting in Wales.
It was a pinching separation to me,
as we had been very nearly bound in gospel fellowship,
in the course of our late arduous engagement.
My brother William kindly accompanied me to Bury, where I informed my friends,
in their monthly meeting, of my prospect in coming among them.
When I had done so, my dear sister Hannah,
who was then on a visit to her sister Martha Brewster, in a weighty manner,
proposed to unite with me therein, which met the cordial approbation of her friends,
and was truly comforting to me.
After meeting, I was favoured to feel such a degree of tranquillity,
as was cause of humble thankfulness.

On sixth-day, we visited three families, and travelled thirty miles.
We continued visiting the families in the country meetings round Bury, until third-day.
That afternoon and evening we had four sittings there;
which I got through under much bodily suffering.
From that time, for several days,
I was much indisposed from a complaint then very prevalent, the influenza;
and my dear sister had something of the same disorder; so that,
visiting the remaining families in Bury,
was all we were able to accomplish in the course of that week.
Under this unexpected detention my mind was mostly favoured to feel peaceful;
and it was a great privilege to us,
that we were so favourably situated as under our
beloved Martha Brewster`'s hospitable roof,
at a time when we were unable to proceed in the prospect before us.
On first-day evening the 17th, I had a meeting at Cockfield,
for some of the inhabitants scattered thereaway; and after it we returned to Bury.

On second-day we parted with our dear Martha Brewster and went to Haverhill.
There we sat with the few families of Friends;
and afterwards attended a meeting with them.
On sixth-day the 22nd, I had a meeting with the inhabitants of Withersfield,
and another village in the neighbourhood of Haverhill.

On seventh-day we went to Sudbury.
With Friends there, and a meeting with the inhabitants of an adjoining place,
we were engaged until third-day the 26th, when we came to Needham.
On the way home,
my mind was so strongly attracted towards some of the inhabitants of these parts,
that I did not feel a full release from this field of labour,
until I had invited them to come together, the following first-day, 1st of fifth month,
when a large number were collected in a barn at Hitcham.
Among them, I believe, was a great variety of states; some, I trust,
awakened seeking minds, though they seemed, as it were, almost lost in the crowd.
Quietness and peace were mercifully vouchsafed to me on my return home that evening:
though I think my mind was never more humbled under
a feeling sense of being but an unprofitable servant,
if at all worthy to be esteemed one in my Heavenly Father`'s house.

My beloved sister Hannah`'s sympathy, and secret exercise of mind,
many times proved strengthening to me, in the course of our moving along:
and I earnestly covet she may reap the reward of solid peace,
for this act of dedication to the precious cause;
which will ever be found enough to recompense for many deeply baptizing seasons.
I trust we may with thankfulness acknowledge,
that although such were sometimes our experience, yet,
the Author of all good was with us at other times,
and refreshed the visitors and visited together, to our humbling admiration.

Though it has been but seldom that I have had any reason to believe
it was right for me to attend our annual meeting in London,
having much oftener apprehended my allotment has been to tarry at home,
while others of our little company in this meeting were so employed: yet, this year,
after the close of the foregoing engagement,
I was unusually led into feeling respecting the approaching yearly meeting;
and my mind was nearly bound in gospel sympathy with my beloved sister Ann,
who was going under a prospect of casting before the select meeting,
her concern to visit the continent of America.
I made some efforts to go which did not succeed, and the time being very short,
I gave it up.
Though I do not know that I can say I felt condemnation,
yet I have not had that clear evidence of being in my right allotment at home, which,
at many other times, I have been favoured to experience.

On fifth-day, the 14th of the seventh month this year,
my dear sister left home for America.
On seventh-day, the 13th of the eighth month, she embarked at Liverpool,
on board the Francis Henrietta, bound for New York.
She was favoured to arrive in safety on sixth-day, the 16th of ninth month.
The loss of her society is great to many of our little circle in this place;
yet the undoubted persuasion that she is led forth by the great Shepherd of Israel,
tends to enable many of her near connections to feel resigned to His unerring will;
consigning her to his fatherly protection,
under every dispensation which he may see fit to appoint
or permit her to pass through for his glorious cause sake;
humbly hoping, in his own time, to be favoured to see her restored to us again in peace.
That her beloved husband, in a peculiar manner,
may be a sharer with her in the precious reward;
and their tender babes know the blessing of preservation,
I feel at the present moment nearly interested,
may be their individual and united happy experience.

Twelfth month, 31st. For some weeks, near the close of this year,
my mind was tried with much deprivation of divine consolation.
But within a few days, it has pleased infinite Goodness,
a little to unveil himself to my comfort, and though it has been but of short duration,
yet enough to renew a degree of living faith, and holy confidence,
in his All-sufficient power, and inscrutable wisdom.
And as it is the frequent humbling experience of his servants,
that it is consistent with his divine will they should live by faith,
it is a mercy which calls for thankfulness of heart,
when any ability is felt in sincerity to utter the submissive language,
under those dispensations, "`Not my will, but yours be done.`" Luke 22:42.
Humbled in the consideration of how frail I am,
and unable in the smallest degree to come to such a state
of resignation without renewed help from time to time,
from the holy sanctuary,
oh! may my mind more and more seek after ability to become sanctified throughout,
in thought, word, and deed.
In reviewing this year,
I perceive that although many deep exercises have been permitted for me to pass through,
yet the Lord has sustained me in the midst of them all;
and I have had some seasons of sweet consolation,
in which my heart has been knit to the beloved of my soul.

First month 1st, 1804.
My mind this afternoon has been led to consider,
that many may be the changes which the present year may produce;
many the trials and exercises I may be permitted to experience.
And oh! may there be a centering to the source of all pure instruction,
for counsel to move according to divine appointment; that whether suffering or rejoicing,
that part destined for immortality,
may be preserved in a state of acceptance with "`the
High and Lofty One that inhabits eternity,
whose name is Holy,`" Isaiah 62:15,
and who still condescends to dwell with them that are of "`a contrite and humble spirit.`"

Fifth month, 11th. In the forepart of this year,
I became renewedly exercised in the prospect of a religious engagement,
which for many years, even from my first appearing in a public testimony in meetings,
has, at times, weightily attended my mind; and particularly in the summer of 1801, when,
for a considerable time,
I was ready to apprehend it would be consistent with my peace to endeavour to move therein.
But infinite Wisdom was pleased at that time to order it otherwise,
as already remarked in these memorandums.
And now, when it first opened with weight,
I felt solicitous that whatever was right in his sight, might be done;
though many have been my fears, as usual under similar impressions,
of being deceived by the great adversary, who cares not by what stratagem he can betray.
At length such became the state of my mind,
under the deep discouragement which I have felt,
that I but seldom possessed any capacity to put up even a secret petition,
to the Father and Fountain of life, for ability to know and do his will: though,
day and night, in company and alone, I had not long together,
felt liberated from an awful consideration of the important subject.
This morning I ventured to unfold to my beloved brother
Samuel a little of my tried situation;
having long looked towards him as a companion,
if ever the way should open for engaging in the prospect in view,
though I knew not that he had ever felt a similar concern.
After speaking to him, my mind, for a short time, was relieved from a very heavy load,
which leads me to believe, let the matter issue as it may,
whether I ever see my way to move further in it or not,
that I have not done wrong in disclosing my feelings to him.
Though he said but a few words on the subject, yet,
from the manner in which he received it, and the weight which accompanied us at the time,
I do apprehend his mind has been somewhat similarly exercised.

Fourth-day, 16th of fifth month.
My brother Samuel revived the foregoing subject to me; and at the same time acknowledged,
to my comfort, that he had for some years felt an apprehension,
that a similar engagement would sometime be allotted him;
but he had not seen the time for moving therein was fully come,
though since I opened my feelings to him,
he has looked more than heretofore towards an early entrance into it;
yet not with sufficient clearness to give me much expectation he
shall be likely to see his way to join me in next eighth month;
which has very much fixed with me as being the right time for my leaving home.
Much do I desire we may both be enabled to move under the direction of Him,
who remains to be, "`Great in counsel, and mighty in work.`" Jer. 32:19.

After many anxious hours, and some deep conflicts of spirit, on this important subject,
I was enabled, at our monthly meeting in the seventh month,
to open my prospect of a visit to Friends and some others in Scotland,
some of the northern counties of England, and the inhabitants of the Isle of Man.
It was received by my friends in a manner that raised
humble admiration in my deeply tried mind;
and casting the burden before them, afforded a precious portion of tranquillity,
to which I had long been much unaccustomed.
I think I never was so sensible of divine help and support, under a similar circumstance,
as in the women`'s meeting at this time,
though I did not feel altogether the same strength in the men`'s.

Indeed I have but seldom felt as much ability in communicating in this way to my brethren,
as when among my sisters: and I believe, the necessity there is, in such cases,
of repeating pretty much the same thing,
does in degree lessen the weight of what is expressed.

My dear brother Samuel, at the same time, informed Friends how he had been circumstanced,
and that he felt most easy to propose to unite with me.
Certificates for us were ordered to be prepared for next monthly meeting,
to be held on fourth-day, the 1st of the eighth month.
