== Chapter IX.

[.chapter-subtitle--blurb]
(3rd of Eighth month, 1804, to the 1st of First month, 1805.)

[.chapter-synopsis]
* Sets out on the visit to Scotland, etc.
* Bury
* Little-port
* Chatteris
* Derby
* Cockermouth
* Parton
* Isle of Man
* Whitehaven
* Dissington
* Cockermouth
* Mary Port
* Cockermouth quarterly meeting
* Graysouthen
* Dundee
* Kinmuck
* Balhalgardy
* Old Meldrutn
* Aberdeen
* Stonehaven
* Montrose
* Dundee
* Perth
* Glasgow
* Edinburgh monthly meeting
* Newcastle
* Shields
* Darlington, etc.
* York
* Wellbourn
* Northampton quarterly meeting
* Chatteris
* Returns home

Sixth-day, the 3rd of the eighth month.
After so long a time of deep exercise,
it has been cause of humble admiration that I have been enabled
to look forward towards the weighty engagement in view,
with so much serene satisfaction, as, for the last few weeks,
has frequently been the happy experience of my thankful heart.
Under these feelings, I left home, and we went this evening to Bury.
The next day my mind was permitted to know a different dispensation,
and I was ready to fear we must part from our dear friend Martha Brewster,
under a sense of the deprivation of that substantial comfort, which,
my soul longed to feel.
But just before we left her hospitable roof,
we were favoured to know a little of the renewed lovingkindness of our gracious Helper,
who, through our beloved friend M. B.,
was pleased to open for us a little brook by the way,
and we bid farewell to her under its tendering influence.

On first-day the 5th, my dear brother Samuel and myself were at Littleport meeting,
which was a very small gathering;
but we were permitted to experience the fulfilling of the divine promise that,
"`Where two or three are gathered together in my name, there am I in the midst of them.`"
Matt. 18:20.
It was a humbling baptizing season;
to be remembered with thankfulness to Him, in whom are all our fresh springs.

We went that evening to Chatteris, and lodged at our friend John Bateman`'s,
who was from home on a religious engagement with John Abbott,
with a view to visit the Isle of Man;
and it now looks likely we may cross the water together.
Before we left this family, we had a humbling opportunity of religious retirement.
In the course of this week we travelled to Sheffield;
taking a week-day meeting at Loughborough, and another at Derby.
At the latter, in the evening of the same day,
we had a meeting with the richly visited inhabitants of that place.

On first-day the 12th, we were at Sheffield meetings.
And from there, on second-day, we went to Huddersfield.
On fourth-day we attended a week-day meeting at Settle; sixth-day, one at Kendal;
and on seventh-day, the 18th, we got to Cockermouth,
where we met our friends John Abbott and John Bateman.
We all attended the meeting there the next day,
and had one in the evening for the inhabitants of that place, appointed by John Abbott.
Though we passed through some close exercise, we had cause to be thankful we were there.
The evening meeting was a time greatly owned by the Shepherd of Israel.

On second-day, we went to our friend Henry Bragg`'s, at Parton, near Whitehaven;
and were informed, on our arrival there,
that the packet for the Isle of Man would sail that evening about ten o`'clock.
This was intelligence that brought my mind under deep exercise,
especially finding all my intended companions were willing to go at that time,
though my brother gave a preference to staying over the monthly meeting at Whitehaven,
the next day.
When I found him so circumstanced, I also endeavoured to look at going with them,
but after a close conflict,
I felt best satisfied to inform my beloved brother and fellow-labourer, that,
before I left home, I thought I saw we were to attend that monthly meeting,
and sail the next day; and that the prospect so continued with me,
as to lead me to believe it was safest to give up going by the packet;
though there then appeared but very little probability of
our getting conveyed to the island on the day I had in view.
My dear brother, when he heard this acknowledgment, felt fully resigned to stay with me.
We then informed our friends John Abbott and John Bateman how we were situated,
desiring them to pursue their own prospect,
if they continued to feel most easy to go that evening;
but they likewise concluded to stay the monthly meeting next day.
It proved a season of divine favour;
and three Friends that day were separated to accompany us,
who proved truly sympathizing helpers many ways, namely, Henry Bragg, John Fletcher,
and Ann Fletcher, the latter as a female companion to me,
whose affectionate attention I have cause to remember with gratitude.
In the afternoon of that day,
Henry Bragg and some other Friends made much inquiry for a vessel to take us over,
but could not succeed;
and late in the evening it seemed needful to give
up the expectation of going the next day.
This was another close trial of my faith,
having so fully believed that we should meet with something suitable for the next morning.
Very soon after it appeared given up by my companion as a hopeless case,
Henry Bragg came in again and informed us he had just met with an offer
of a vessel to take us either that evening or the next morning.
We soon concluded to take the morning`'s tide;
and I went to bed with a heart filled with thankfulness and peace.

Fourth-day morning, the 22nd, we sailed from Whitehaven with a fair wind,
and very fine weather, which continued until we got about two-thirds of the way over;
then it became almost a calm; and when a little wind did spring up,
it was nearly a-head of us, which made it slow getting on.
However we were favoured to land safe at Ramsay, thirty-four miles, that night;
and had cause to feel our hearts humbled in thankfulness to Him whom,
wind and waves obey.

We had a meeting at Ramsay the next morning, and another in the evening;
in both which we experienced Holy Help to be near.
At this place we met with great kindness from a family
who accommodated Ann Fletcher and myself with a bed;
and manifested other acts of benevolence to our little company,
which bound them to our affectionate and religious feelings.
With them we had a solid season of retirement before we set off on sixth-day morning,
in which they were recommended to seek more and more
after an inward acquaintance with the Father of spirits,
who is the sure reward of all his faithful people,
and worthy to be served both by the aged and the youth.
Intercession was also made unto Him, that,
as they had handed much more to us than a cup of cold water, in the name of disciples,
they might receive their reward; and that he would be pleased to grant us, his pilgrims,
the blessing of preservation under all our movements,
in passing along through this little island, a very small part of his foot-stool.

On sixth-day evening, we had a meeting at a place called Kirk Andrews.
On seventh-day evening, one at Kirch Michael.
On first-day morning the 26th, we had a meeting at Baliff; and in the evening,
one at Peeltown, where we met with several solid people among the society of Methodists;
with whom we were permitted to experience, in a very precious manner,
the overshadowing wing of divine regard; under the influence whereof,
ability was granted, to espouse the truths of the gospel, given to us as a people,
in a peculiar manner, to bear unto the world.
Under a humbling sense of his goodness,
and of our unworthiness of his multiplied favours,
the tribute of thanksgiving and praise was offered unto his glorious name,
who is forever worthy of all that can be ascribed unto him.
After meeting we sat a while with one family of the aforesaid people;
where we were again permitted to know,
that our Holy Helper is confined neither to time nor place;
but is condescending to deal out his bread to the hungry,
when and where a due preparation is made to receive his bounty.

On second-day morning,
I arose under an awful apprehension that it would be right for at least a part
of our company to go again into the family we had visited the preceding evening,
and into some others among that people, before we left the place.
After breakfast I mentioned this to my companions collectively;
and I had the satisfaction of finding my beloved
brother had received somewhat of a similar impression.
After solid deliberation, part of our band concluded to accompany us,
while Henry Bragg and John Fletcher went to a place a few miles distant,
in order to provide a meeting for the evening.

We went first to the family we had been with the evening before,
where we again met a very cordial reception.
We had also the company of their parents, who resided at the next house;
and of a solid young man, their preacher.
With them altogether, we were favoured to have a truly solemn and profitable opportunity;
at the close of which, apprehending we were with some of the heads of their tribe,
my brother felt it safest to remark to them a custom we had observed in many places,
and particularly on this island, which was of those in their society,
when they attended our meetings, kneeling down on their entrance into the room.
He pointed out the difference we felt towards different individuals under this ceremony;
some we had cause to believe felt an awful sense of the object of our meeting together;
but with respect to some others, their manner was so irreverent,
as to cause us to feel deep lamentation on their account; and in some meetings,
we had believed it right at the close of them,
to give a caution against complying with such an outward form,
while the attention of the mind was far from the great object of adoration and worship.
Under a feeling of near regard, we parted with them all, except the young man,
who kindly conducted us to the other families which we visited:
wherein also we experienced the gathering arm of Israel`'s Shepherd.
The more we saw of this young man, the more we felt bound to him in gospel love,
in a sense whereof we bade him farewell.

That evening we had a meeting at Malinaclig.
On third-day evening one at Darby, with some solid people,
but among them we apprehended there was a great diversity of states.
It proved, however,
a season wherein divine mercy appeared to be near to do the people good.
Even some such as had been too much in danger of resting satisfied with former
experience of the great Master`'s gracious visitation to their souls,
without endeavouring to maintain the watch against a situation,
comparable with that of those who thought themselves rich and increased in goods.

As there was not a place of public entertainment in this village,
we were here for several hours taken in by a man and his wife, John and Eleanor Ellison,
who appeared to be of truly religious minds.
With this family, after a meeting held in the place, we parted,
under evident marks of affectionate esteem; and had a beautiful moonlight ride,
several of us in an open cart; but tranquillity covering our minds,
though it was past midnight before we arrived at our proposed lodging place,
we enjoyed our situation.
On fourth-day, we had a meeting at Castletown in the morning,
and one in the evening at Ballamodda; fifth-day, at Ballanorrass; sixth-day,
at Ballasalla; and on seventh-day evening, the 1st of ninth month,
we had our last meeting on this island, expecting to sail that night for Whitehaven.

This meeting was held in a large assembly room at Douglas,
and for some time after we met,
it was the most unsettled opportunity we had known since our landing on the isle.
Indeed, it was so much so, as to plunge my mind into deep discouragement,
considering that we could not have another meeting with the inhabitants of that place,
without missing our conveyance by the packet.
I think it was a season of as close exercise as I ever remember to have experienced.
John Bateman and my dear brother, had each a little matter to offer to the people,
I thought very pertinent to the situation of several among them, whose states,
as to religious sensibility, I believe, were very different;
some of them appearing awfully aware of the intention of our gathering together.
However,
so little place did the foregoing testimonies appear to have with those of another description,
that soon after my brother had taken his seat again,
I was ready to apprehend it might be best to close the meeting,
but my companions did not feel at liberty to do so.
After endeavouring to bear my burden the appointed time,
I at length believed it would be safest for me to at least get upon my feet,
which I did in much fear and trembling; but with an earnest desire,
to be rightly directed by Him, who only knows the food convenient for his people.
Probably the novelty of a female`'s appearance in such a manner,
might have place with some of them, so that in a short time they became much quieter,
and more attentive; and I was enabled to minister to many different conditions present,
to the relief of my own mind.
After this, some further communications were offered by my fellow-labourers;
and the meeting ended in solemn supplication to our universal Parent,
for a blessing on the present opportunity:
and in humble acknowledgements for his gracious assistance unto us,
mercifully vouchsafed at that time,
as also on many similar occasions in our passing along,
among the little handful of his people situated on that small spot of ground.
We took an affectionate leave of many after meeting; and on our way to the inn,
called at a house where we had that afternoon taken tea,
with a very valuable young woman and her aged father;
with whom we now had a solid and truly memorable season of religions retirement.

When we reached the inn,
we were immediately told the captain had been there to inform us lie was ready to sail.
We were therefore obliged to leave the house without sitting down,
or partaking of any refreshment for the body;
but our minds being richly replenished with a portion of peace,
and feeling a full clearance of that part of our mission,
it was of but very little consequence to us.

We went on board about ten o`'clock, and after a good sail, with a fair wind,
were favoured to land in safety at Whitehaven, at nine o`'clock on first-day morning.
After breakfast, my brother and myself went to our friend H. Bragg`'s, at Parton,
to get a few hours rest.
In the afternoon we assembled with our friends at Whitehaven.
That day, before we parted with our friend John Abbott,
he informed us of a prospect he had,
of a meeting with the inhabitants of a village between Whitehaven and Cockermouth,
querying if we had had any view towards the same place.
As it had attracted my attention,
so much as to lead me to apprehend we should not be likely
entirely to leave those parts without a similar engagement,
it seemed, we thought, very desirable to unite with him and John Bateman;
though I felt so fatigued and in need of rest,
after our close travelling and exercise on the island,
as rather reluctantly to submit to joining them in the appointment of a meeting there,
Dissington, on second-day evening; which appeared the most suitable time for them.
It proved to me a particularly exercising meeting,
wherein I thought I had to labour in the gospel,
in as much weakness and mortification to the creaturely part,
as at any time since my leaving home.
Indeed I was almost ready to call in question the rectitude of our being there; but,
after we left the place, and returned to Parton,
I was permitted to feel a degree of the calming influence of divine love,
as a canopy to cover my mind, so as to raise reverent thankfulness to Him,
who is pleased to accept the feeble,
if but faithful endeavours of his humbly dedicated children.

On third-day we all attended the week-day meeting at Cockermouth,
where we met our three kind fellow-helpers, who had accompanied us across the water.
In the afternoon we had a precious parting opportunity together;
in which we had to acknowledge that the sustaining arm of
divine sufficiency had been with us in our going forth,
and mercifully supported throughout;
sweetly uniting our little band in gospel fellowship.
We had also to acknowledge that many circumstances respecting our union,
had been marvellous in our eyes,
and claimed the tribute of gratitude and praise to our Holy Director,
who remains to be unto his people, "`Wonderful, Counsellor,
the Mighty God;`" Isaiah 9:6, and who was condescending, at that time,
to bestow a portion of enriching peace; though we could truly, with abasedness of spirit,
adopt the language, "`We are unprofitable servants;`" Luke 17:10.

On fourth-day, John Abbott and John Bateman went to Kendal;
and my dear brother and myself to a meeting at Setmorthy.
In the afternoon, in our way to Broughton, we visited a very afflicted Friend,
I think the most pitiable object I ever beheld;
but we were comforted in believing his sufferings
would terminate with his existence here;
and we also were ready to believe that it would not be very long
before the gracious call would be in mercy extended to his soul,
to leave the shackles of mortality, for an abode in durable happiness.

From fifth to seventh-day, we attended meeting at Broughton, Pardshaw, and Grey-Southen.
On first-day the 9th, we were at Maryport.
In the morning meeting there, I very soon felt my mind under exercise,
and several states present were brought before me
with what I apprehended clear openings for communication;
but I had not been sensible of the full time being come for it, when another stepping in,
closed up the way, and we had no public labour there.

In the afternoon meeting we were permitted to experience a good degree of relief,
although I do not suppose we were endowed with as much strength, to warn some,
and encourage and sympathize with others, as we might have been,
had we met with no impediment in the foregoing meeting.
However, we had renewed cause, through all, to thank our gracious Helper,
and to confide in his all-sufficient power.

On second-day morning, after a season of divine favour,
in the Friend`'s family where we lodged, we left Maryport.
In the remaining part of this week we visited the meetings at Allanby.
Holm, Wigton, Bolton, Kirkbride, Coldbeck, and Mosedale.
On first-day the 16th, we were at Carlisle, in the morning;
and had a meeting in the evening at Scotby.
On second-day, we travelled over some very mountainous road to Aldston;
where we had a meeting the next day.
Fourth-day, we were at monthly meeting at Allondale;
and in the afternoon attended a select meeting there, held in a Friend`'s house,
to accommodate an ancient woman who was not able to get to the meetinghouse.
On fifth-day, we had a meeting at Derwent, and returned to Allondale.
Sixth-day evening we had a meeting at Cornwood.

In the course of the last two weeks, many have been our exercises.
In some of the meetings we have attended, within that time,
we have been favoured to feel, concerning a few individuals,
that the pure cause which we are engaged to espouse, is lovely in their view.
But, alas!
By many others it has appeared to be professed only by tradition.
They hardly seemed sensible of the lamentation we were constrained at times,
to utter in their hearing; and in one meeting in particular,
we had cause to fear from the impressions we felt, that the enemy of all good,
had so far prevailed with his temptations,
that some were not clear of all unseemingly and immoral conduct.
May the God of all grace,
still be pleased so to plead with these his poor bewildered children, as,
by his powerful and delivering arm,
to preserve them eventually from the jaws of the devourer;
through a timely obedience to his gracious precepts and invitation:
"`Wash yourselves, make yourselves clean;
put away the evil of your doings from before my eyes;
cease to do evil; learn to do well.
Come now, and let us reason together, says the Lord: though your sins be as scarlet,
they shall be as white as snow; though they be red like crimson,
they shall be as wool.`" Isaiah 1:16-18.
Even unto such as these, his subsequent promise is,
"`If you are willing and obedient, you shall eat the good of the land.`" Isaiah 1:19.

On first-day the 23rd, we were at Sykeside meeting in the morning;
and in the evening attended one at Sol port; after which we returned to Sykeside.
On third-day we had a meeting at Moorhouse;
which concluded our visit to all the particular meetings
in the quarterly meeting of Cumberland and Northumberland.
This week the quarterly meeting was held at Cockermouth;
and after many days of considerable thoughtfulness on the subject,
it seemed best for us to attend that meeting before we proceeded for Scotland,
which we accordingly did on the 27th and 28th of ninth month.

On seventh-day morning, after a solid opportunity in J. and D. Ritton`'s family,
where we had been several times entertained with much kindness and affectionate attention,
we left Cockermouth for Parton, and there,
in the agreeable society of our dear friends H. and M. Bragg, and their children,
we spent a quiet afternoon.
On first-day morning, we attended Whitehaven meeting,
which proved a season of relief and consolation to our minds,
not having felt fully clear of Friends there until now.
In the evening we had a very large meeting with the inhabitants of Workington,
and went after it, though late, to Grey-Southen, to our kind friend John Fletcher`'s.

Tenth month 1st, second-day.
This evening we had a meeting with the inhabitants of Brigham,
at the close of which we parted with several Friends who met us there,
to whom we had been nearly united in gospel fellowship;
expecting the next morning to leave those parts, and go directly for Scotland.

On third-day we were accompanied one stage on our way, by our dear friend John Fletcher.
On the road we were overtaken by H. Bragg, who intended to accompany us to Edinburgh.
We got that night to Carlisle; and on fourth-day morning,
after a little season of retirement,
we parted with our kind friend David Carrick and his family.

A few miles from Carlisle,
H+++.+++ Bragg proposed our calling to speak to a Friend`'s family by the road`'s side,
with which we complied; and were well satisfied in doing so.

This afternoon we entered into Scotland; and on fifth-day we reached Hawick,
where there are two families of Friends, who sit down together in one of their houses.
That evening we had a public meeting there;
and the next morning sat with the two families in that place separately,
in which we felt satisfaction; and under a feeling of gospel love, we parted with them,
except one Friend, who went with us to Edinburgh, where we arrived before dinner,
on seventh-day.

On first-day the 7th, we attended the meetings there.
In the morning sitting I was dipped into close exercise,
without any opening for communication, and the watch word which deeply impressed my mind,
appeared to be like the injunction given by our Great Master, to his immediate followers,
when they were about to enter upon his mission to the lost sheep of the house of Israel:
"`Be therefore wise as serpents, and harmless as doves.`" Matt. 10:16.
This was accompanied with an awful impression,
that to do our proper business, we must submit to visit from house to house,
among our friends in that place.
Before the afternoon meeting, I felt a necessity to unfold to my beloved brother,
how I was circumstanced, who, I found, had been in somewhat a similar situation,
but did not appear to be come at full clearness in his mind respecting it.
This I much desired he might be favoured to do,
before any such prospect was opened to our friends;
though I apprehended it might be right for us to commence our visit that evening,
and thought I saw with what family we should begin;
yet I could not feel satisfied to divulge it further, until his way was perfectly clear.
However, after I had informed him what I did,
I experienced a degree of relief from the weight of exercise which had rested with me,
previously to my speaking to him on the subject.
But it was otherwise with him, for he found the matter increase, and fix so much,
that at the close of the afternoon meeting, in a very desirable manner,
he informed friends of our prospect.

From some of them we received expressions of sympathy,
and encouragement to pursue what we had in view; and it was by them proposed,
as we should need some assistant to conduct us from one family to another,
that our friend Henry Bragg, who had kindly accompanied us many miles, should,
if he felt freedom so to do, aid us a little longer,
by continuing with us through the impending engagement.
To this he readily assented, and that evening we sat with two families.
Second, third and fourth-days, were employed in this way.
On fifth-day, we attended a monthly meeting at Edinburgh;
and in the evening had one sitting.
At the close of that day, we felt, at least, a present release from this place;
and had cause to testify that the Lord God Omnipotent, is worthy to be sought unto,
and trusted in, by his children and people.
And, oh! may we prove humble and grateful receivers.

On sixth-day and seventh-day, we travelled to Dundee,
accompanied by Alexander Cruikshank, our kind landlord at Edinburgh;
we had also the company of our friend Henry Bragg,
who did not yet appear prepared to bid farewell to us.
On first-day the 14th, we attended two meetings at Dundee,
and had two sittings in Friends`' families.
On fourth-day we got to Balhalgardy, to our friend John Cruikshank`'s,
under whose quiet roof I felt it a peculiar privilege to shelter that evening,
being very unwell with a close cold,
and much depressed in mind in the prospect of the remaining engagements in this land.

On fifth-day we rode five miles to Kinmuck,
in order to attend a monthly meeting there that day; but I was too ill to go to meeting,
or to keep out of bed much of the time Friends were sitting; yet,
obtaining a little relief in the afternoon, we went five miles further to Old Meldrum.

On sixth-day we had a meeting there;
and after a religious opportunity with a friend before dinner,
and an opportunity after it with the family where we lodged,
we essayed to leave that place; but I could not, with satisfactory clearness,
see our departure from there,
without visiting the rest of the little handful of professors under our name,
belonging to that meeting; with which my brother united.
We got through them that evening and the next day; and afterwards returned to Balhalgardy.
On first-day the 21st, we were at the meeting at Kinmuck,
which I think was in some good degree owned by the great Shepherd of Israel,
and ended to satisfaction.

As I continued to feel very unwell, after meeting we went back to Balhalgardy,
and rested there the remaining part of that day.
Indeed I was ready to suppose, I must tarry there many days,
before I should be well enough to move forward,
with what still remained to do thereabouts.
But I recovered so far, as to get to a public meeting appointed for us at Old Meldrum,
on second-day evening; and though it was very wet, without taking any fresh cold.
On third-day we had several sittings with the families
within the compass of Kinmuck meeting;
and the remaining part of them, we sat with before their meeting on fourth-day,
which we attended.
In the evening we had a public meeting at Inverary.
The latter proved a season of some encouragement to my mind,
feeling Holy help to be near,
which remains to be a rock of defence to the truly dependent in all their exercises.

After this meeting we went to Balhalgardy.
The next day we parted with our kind and much esteemed friends of that family,
with whom we had a solid season of retirement when about to separate,
which to us felt a comfortable close to our little services thereaway.
On sixth-day we had a meeting with Friends at Aberdeen,
where some of the few professing with us, appeared very much strangers to the pure truth.
It was an exercising meeting; but some ability was afforded to labour;
and in it we had peace.
We felt much sympathy with one individual,
in whose family we had a religious opportunities before we left the place,
in the afternoon.
That evening we visited, at Stonehaven,
the only remaining member of Ury meeting--a very ancient woman;
but it was comforting to our minds, to find, in her very lonely situation,
she was favoured, in her old age,
to retain a lively sense of the pure principle in
which she had for many years professed to believe.
This was now her comfort and support;
and we had a comfortable hope would be mercifully
vouchsafed to the end of her pilgrimage here;
and that at the close thereof she would obtain an admittance into the kingdom,
where sorrow and sighing are no more.

On first-day the 28th, we had a meeting with the inhabitants of Montrose,
which to me was a very trying one, believing but a small number,
in a large gathering of people, were heartily engaged for their own eternal interest.

On third-day the 30th,
we had an open and satisfactory meeting with some of the inhabitants of Dundee;
in a part of the town, where no meeting of our Society had of late time been held.

Eleventh month 1st, and fifth of the week, we attended a meeting at Perth,
with a small number in profession with us, among whom we had some exercising labour.
My mind was led much to fear for an individual in particular, who, I believed,
in days past, had known a beginning in the spiritual warfare;
but who appeared in considerable danger of cherishing
a propensity to be "`now made perfect by the flesh.`"
Gal. 3:3. This Friend coming to our inn,
I had an opportunity with him which proved relieving to my mind.
The word preached did not appear to have much entrance into the hearts of some;
but blessed be the name of Him, whom I desire to serve, not the fruits of our doings,
but the faithfulness of our hearts,
commends his dedicated servants to his divine acceptance.

On first-day the 4th, we attended two meetings with our friends at Glasgow,
besides sitting with them in their preparative meeting.
In the evening we had a solid opportunity in one of their families,
when several others of them were present.
On second-day morning, the way did not appear clear to leave them,
neither could I see enough light upon visiting their separate families,
to admit of my proposing it to my dear brother;
but I soon found he had more fully received the word
of command to go among them in that way.
Having felt so much as to enable me cordially to unite with him, we, without delay,
entered into the work, that we had cause to believe was assigned us.
On fifth-day the 8th, we attended a second monthly meeting at Edinburgh,
where Ave were renewedly led into much exercise.
Both our minds were so closely arrested in our separate apartments this day,
as to lead us to suppose we should not be clear,
without attempting to dip a little further into their situation,
than we could do in their monthly meeting.
This we did in much fear,
and with an earnest desire to be preserved from hurting the pure cause,
if we were not permitted to promote it, or help our friends;
to all of whom we felt much love.
On third-day morning the 13th, my dear brother and myself left Edinburgh,
after a little season of retirement, in which we had the company of dear H. Bragg,
who had continued with us until this time,
and was particularly helpful to us in the late arduous engagement.

On sixth-day evening the 16th, we got to Newcastle, and the 17th, rested there;
which was the first day we had spent since we left home,
without either religious engagements, or travelling, or both.
On first-day the 18th, we attended two meetings there;
wherein some ability was afforded to sympathize with the rightly exercised in that place;
and to hand a word of encouragement unto such, to hold on in the line of manifested duty,
for the promotion of the blessed cause in themselves and others.
A caution was extended to some among them,
to guard against a disposition which might lead to procrastination,
in the very momentous concern of preparing for a future existence:
and some other states present were, I trust, ministered to in the love of the gospel.

On second-day we had a meeting at Benfieldside.
Third-day, after some religious opportunities at Newcastle,
whereto we returned the preceding evening, we went to Shields.
On fourth-day, we attended the week-day meeting;
and before we left the place in the afternoon,
had a solemn season of retirement in Henry Taylor`'s family,
whose daughter I had felt deeply for, she being in a very delicate situation;
and I was apprehensive, not likely to be again restored to stronger health.
My brother was led to address both her and her father in an affectionate, and I thought,
a very suitable manner,
after which I felt my mind strengthened to supplicate at the footstool of Divine mercy,
that whether it might be consistent with the will of Him, who does all things right,
to lengthen the thread of life to more advanced age,
or cut it short in the bloom of youth,
her way might be clear to the glorious abode of sanctified spirits.

The five following days we had meetings at Sunderland, Durham, Auckland, Staindrop,
and Cotherstone.
On third-day the 27th, we attended a monthly meeting at Staindrop;
and on fifth-day the 29th, were at the week-day meeting at Darlington,
which we sat throughout in suffering silence, except a short sentence,
delivered by my brother, at the close of the meeting.
After some deep wading, and heartfelt exercise,
we both apprehended the way to obtain a little relief,
pointed towards visiting the most active members in their separate families.
This engagement occupied sixth and seventh-days.
On first-day, the 2nd of twelfth month, we attended the meeting there,
which with three private religious opportunities that day,
opened the way for our liberation from there on second-day;
and that evening we went to Stockton.
The next and two following days we were at meetings at Norton, Stockton, and Yarm.

In the course of this journey I have experienced many very trying,
and in some sort new exercises; and I think those which I have passed through,
in these parts, have sometimes been as deeply distressing as any I have ever yet known;
but so it must be, where the pure seed is in captivity in the hearts of the people;
and a favour it is to be found worthy to suffer with a crucified Lord.
However, some rightly exercised travellers, I believe, are preserved among them,
for whom I feel near sympathy; much desiring they may hold fast their confidence in Him,
whose arm of all-sufficient power is still able to
support his humbly depending little ones,
under all tribulations which they are permitted to pass through for his pure cause sake.
Such indeed may be comforted in the gracious promise,
that "`though a woman may forget her sucking child,
yet the Lord will not forget`" (Isaiah 49:15) those,
who are rightly concerned for Zion`'s prosperity.

On first-day the 9th, we were at Whitby; and on fourth-day the 12th,
after a meeting at Malton, we went to York.
Here we stayed two days with our relations and friends.
On seventh-day the 15th, accompanied by Henry Take, we went to Doncaster,
We stayed first-day there, and attended the meetings,
which by me were passed in silent exercise.
The next morning we parted with Henry Tuke, he returning home,
and we going towards Lincoln.
There, on fourth-day the 19th, we attended a quarterly meeting,
with a small number of Friends, to some solid satisfaction.
On fifth-day,
we called and spent two or three hours with our kind and valuable friend Alice Burtt,
at Welbourn; and before we parted,
we had renewed cause to acknowledge that the presence
of the Most High is not confined to time or place;
feeling, with her and her family, such a degree thereof, as, I trust,
will enable the visitors and visited to retain a lively remembrance one of another.

On seventh-day evening the 22nd, we got to Wellingborough.
On first-day we attended the meeting there.
In the afternoon we went to Northampton.
That evening we attended the quarterly meeting of ministers and elders there;
and the next day the quarterly meeting for worship and discipline.
This to me was a low time;
yet it did not appear right to withhold communicating a
little of my small stock of spiritual bread to others,
though not to much relief But, in the afternoon, just before we left the place,
in a religious opportunity, in the family where we lodged,
several other Friends being also present,
I obtained an increase of that substantial food,
which enabled me to leave them in thankfulness and peace.

We returned to Wellingborough with our much-esteemed friends B. and T. Middleton.
On third-day we attended a week-day meeting at Finedon, and after it,
and a season of retirement in a family there, we went to Thrapston.
On fourth-day we reached Chatteris, where we spent a very pleasant evening,
with our late ancient companion on the Isle of Man, John Bateman; who, we thought,
appeared to be reaping a reward for his evening`'s sacrifice.

On seventh-day evening the 29th, we were favoured to get well home;
and had the satisfaction of meeting our relations and friends in usual health,
and from them a very cordial welcome to Needham again; which,
with the merciful preservation dispensed to us in our long travel,
calls for humble thankfulness to the Author of all our blessings.

On third-day the 1st of first month, 1805, we attended our monthly meeting at Woodbridge,
and returned our certificates; which as far as related to myself,
was under the humiliating sense of unfitness,
and incapacity for the great work in which I had believed myself required to engage,
for the promotion of the most dignified cause which can be espoused on earth.
Yet in retiring from the field of labour, and settling down at home, my mind, at times,
has been favoured to partake of a degree of peaceful tranquillity.
This is not at our own command; and therefore,
when it is graciously vouchsafed should be accepted with gratitude and praise,
as from the treasury of Him,
who is a rich rewarder of them that diligently seek and serve him,
with integrity and uprightness of heart.
