== Chapter X.

[.chapter-subtitle--blurb]
(First month, 1805, to the Ninth month, 1806.)

[.chapter-synopsis]
* Elizabeth Gibson`'s burial, and that of another individual
* Her sister Ann returns her certificates.
* Quarterly meeting
* Accompanies W. Forster, Jr.
* Quarterly meeting
* Earith

Within a week after my brother and I had returned from our journey into Scotland,
we left home again, accompanied by our dear brother Dykes,
to attend the interment of our much beloved friend Elizabeth Gibson, of Saffron Walden,
who was removed after about a week`'s illness.
She was far advanced in life, being in the seventy-sixth year of her age.
Her faculties, both spiritual and natural, remaining very bright to the last,
she will be much missed in the militant church; yet,
as there is no doubt of her happy admittance into the church triumphant,
we have no cause, on her account, to mourn;
believing she was ripe for a glorious transition
from the troubles of time to the joys of eternity.
She was permitted to put off mortality in a remarkably easy manner,
without the least apparent suffering at the final close.

Many friends from different parts attended, and the meeting, in the early part of it,
was solemn.
Under this precious feeling, dear Mary Pryor of Hertford,
delivered a very lively and heart tendering testimony;
but for lack of all keeping their proper ranks, I believe we lost, in some measure,
the favour designed for us by the great Head of the Church;
yet the meeting was permitted to end under a covering of good.
And at the grave side, an awful silence prevailed,
and two short testimonies were there delivered,
before we quitted the remains of the dear deceased.

In the twelfth month this year,
my brother Samuel and myself attended the interment of +++_______+++, and had cause to believe,
that after all the vicissitudes he had been permitted to experience,
during his long pilgrimage here, both in spiritual and temporal concerns,
he was mercifully favoured to know his transgressions to go before-hand to judgment,
and to obtain a seat within the glorious confines of eternal felicity.

We had a solid meeting on the occasion,
and I believe many minds present were led seriously to consider their latter end.
And some of us were enabled to feel a tribute of
thankfulness raised in our hearts unto Him,
whose "`mercy endures forever.`"
Psalm 136.

At our monthly and quarterly meetings in this month, my beloved sister Ann Alexander,
delivered up the certificates she had received from these meetings,
in order to visit America,
and produced several testimonies from there of her acceptable services in that land.
She also spread before us a humble, lively, and animating account of her exercises,
merciful preservations and divine support;
acknowledging to the sufficiency and goodness of that power,
who had enabled her to leave all and follow Him, and who had brought her home in peace.

Sixth month, 1806.
For a considerable time past,
my mind has mostly been permitted to know a season of deep depression,
and great deprivation of religious comfort.
In this state I went to our quarterly meeting held at Ipswich, this week;
where I was favoured, in some of the sittings thereof,
to experience a revival of gracious communion with the Father of spirits, which,
in my drooping condition, was a renewed mark of his merciful condescension,
that calls for humble gratitude.
In our women`'s meeting,
I felt strengthened to advocate the noble cause we were met to promote;
and towards the close of it, my heart and knees were bowed in awful thankfulness,
to the great Master of all rightly gathered assemblies.
I apprehend we were favoured with rather an unusual covering of good;
under this we closed,
and I trust many of us were enabled to separate one from another with
a tribute of praise to the bountiful Dispenser of his own precious gifts.
In a more than common manner,
has the consolation of that day been permitted to continue uninterruptedly with me.
Oh! that I may prove a grateful receiver of this most desirable visitant;
and stand unreservedly resigned to all the future
dispensations of his unerring wisdom and goodness,
says my soul, Amen.

In the forepart of the seventh month, I accompanied Wm. Forster, jun.
to several public meetings within the compass of our monthly meeting;
and towards the close of it, I met him at Tivetshall,
and was with him a few days while he was in that neighbourhood,
engaged in the same weighty service.
This I had reason to believe he was favoured to feel very important;
in an especial manner for one so young in years,
and so recently called to a public espousal of the cause of righteousness and peace.
Though the meetings he appointed were not all owned with the same degree of Divine influence;
yet, I think, there was not one, either about us, or in Norfolk,
that I could doubt the rectitude of his holding.
Some of them were in a very precious manner sanctioned
by the presence of the glorious Shepherd of Israel.
Yes, it sometimes rejoiced my heart to see and feel one in the days of youth,
so dedicated to the most noble cause, and so strengthened to espouse it.
Humbly do I crave that the blessing of preservation may be his happy experience.
May ability be granted to keep near to his holy Director,
that thereby he may be favoured to detect our common enemy, in all his appearances;
and so the good work begun in his heart, may be carried on to the praise of Him,
"`whose reward is with him,
to give every man according as his work shall be;`" Rev. 22:12.
The "`Alpha and Omega,
the beginning and the end, the first and the last.`"
The all in all to those who serve him with integrity.

In the retrospect of the time we spent together,
my mind has sometimes been permitted to possess such a portion of tranquillity,
as leads me to hope I was not moving out of my right allotment,
in endeavouring to hold up the hands of this my junior friend,
under the exercise which I believe he was called
to bear by the great Father of the spiritual family.

Ninth month, 27th. At our quarterly meeting last week, very different was my situation,
to that which I experienced in the foregoing one.
I think I have not often, if ever,
sat through the several sittings of a quarterly meeting
with so little truly religious feeling.
But I believe many others were permitted to obtain a morsel of spiritual food;
both immediately from Him, who is to his people, "`food indeed,`" John 6:55,
and through the ministry of some rightly qualified servants.
Many the are dispensations expedient for some to pass through,
in order to become altogether sanctified and fit for the kingdom undefiled.
Oh! gracious Father, permit not your hand to spare,
until all in me is removed which is contrary to your pure and blessed will!

After the quarterly meeting, though in a tried and stripped state of mind,
I went with my brother Samuel in order to attend
the marriage of Lovell Squire and Sarah Brown,
at Earith.
There, on the day of their union,
I apprehended I received some small commission to espouse the good cause;
but in so much feebleness as to lead me to fear the rectitude of my movements: however,
at the close of the evening,
I was mercifully favoured to believe I had done what was my duty to do, and no more,
which afforded a ray of comfort to my drooping mind.

Since our return home, though still low and poor,
I feel satisfied that I complied with my brother`'s request to accompany him.
Much do I desire the dear young people, who are just entering into life,
and whom I much esteem, may be disposed to "`seek first the kingdom of God,
and his righteousness;`" Matt. 6:33,
unto which state is subjoined the gracious promise, that,
all other necessary blessings shall be added.
