== Chapter XI.

[.chapter-subtitle--blurb]
(3rd of Twelfth month, 1806, to the 8th of Fourth month, 1807.)

[.chapter-synopsis]
* Reflections on a prospect of visiting London and Middlesex quarterly meeting, etc.
* Tottenham
* Plaistow
* Tottenham
* Southgate
* Grace-Church-Street monthly meeting
* Colchester

Twelfth month 3rd, 1806.
Yesterday I found strength to unfold to my friends, at our monthly meeting,
a religious prospect which has long been weightily before me,
to visit the families of Friends in three of the monthly meetings,
constituting a part of London and Middlesex quarterly meeting, namely,
Grace-Church-Street, Tottenham, and Barking; extending also to some other services,
particularly to visiting the families of Friends at Colchester.

Awful indeed has been, and still continues to be,
the view of this very important engagement.
The prohibition which I feel to take any thought about a help-mate for the work, has,
at times, added to the weight thereof; yet, at some other seasons,
when I am enabled to attain to that state of pure submission,
wherein I can say to Him who is infinite in wisdom and goodness, "`Not my will,
but yours be done,`"
Luke 22:42, I have sweetly felt ability to adopt as my own,
an expression of Job Scott`'s: "`Quietness, as a canopy covers my mind.`"
When this calming influence prevails, I feel an unshaken persuasion,
that all things needful will be provided.
Oh! that my mind may be preserved so steadily fixed on the immovable Rock,
that whatever adverse gales may be permitted to blow,
my trust and hope therein may prove "`as an anchor of the soul,
both sure and steadfast,`" Heb. 6:13. I can hitherto acknowledge the goodness of Him,
who, I humbly trust, has called for this surrender of my will to his all-wise disposal,
in having granted me a little portion of peace,
since disclosing to my friends a willingness once more, in this way,
to prove my attachment to that cause,
which I sometimes feel dearer to me than my natural life.

At present,
it is my expectation to commence the visit with attending Tottenham monthly meeting,
at Waltham Abbey, on fifth-day the 8th of the first month, 1807.

Tottenham, second-day, 12th of first month.
This evening I have parted with brother Samuel, who, in his customary kindness,
accompanied me from home last third-day, and the next afternoon we reached this place.
On fifth-day we attended the monthly meeting at Waltham Abbey,
where I produced my certificate, and I trust,
obtained the sympathy of some of my brethren and sisters in this part of the vineyard.
I had also the satisfaction to find my friend W. Forster, Jr.
was bound to a part of the families thereabouts.
We commenced our visit on sixth-day morning, when my brother left me for two days,
and we met again at Winchmorehill on first-day.
We all attended the meeting there,
and in the evening had a large assembly of those not in profession with us.
This morning we were all at the meeting of ministers and elders in London,
and came to Tottenham to dinner.
With so weighty a prospect before me, it feels pinching to part with one, who,
both in natural and religious bonds, is so near to my heart, as my dear brother Samuel.
But on that Arm of Power which has hitherto supported, I desire to rely.
Humbly craving his holy aid,
quietly to endure every dispensation of his gracious Providence,
both in heights and in depths.

Plaistow, third-day, 20th of first month.
Though I had not got through my engagements in Tottenham quarter,
I felt bound to attend a monthly meeting here today.
After the reading of my certificate in both meetings, a committee was appointed in each,
to render the needful assistance in the performance of my engagements in Barking quarter;
and in a conference which I have had with the joint committee,
I ventured to open a little prospect I have for some time seen,
of having the company of my friends John and Tabitha Bevans, in the families hereabouts.
I also then informed my friends,
that I expected to visit this monthly meeting before I returned to Tottenham,
and to commence the engagement tomorrow morning.
My proposals were cordially received, and united with by the committee;
J+++.+++ and T. B. being of the number,
and acquiescing with the part which more particularly applied to them.
All this proved relieving for the moment: but, alas! my mind, this evening,
is so reduced and brought into deep exercise,
that I scarcely am able to believe that I ever was
acquainted with the voice of the Good Shepherd,
I am almost ready to conclude that all I have felt concerning my present awful engagement,
and everything of a similar nature,
have had their origin in the grand deceiver of mankind,
who cares not by what bait he prevails over the children of men to follow him,
thereby alienating the soul from the bountiful Source of all substantial good.
Oh! you who can search the secret recesses of every heart,
permit me to know your blessed will,
before I get so entangled with the power of darkness, as, in any wise,
to bring reproach on your precious cause,
which you know is more dear to me than my natural life;
for this I could willingly surrender this night,
rather than remain here to harm the pure testimony of truth.

Tottenham, third-day, 3rd of second month.
Yesterday I closed my visit to Barking monthly meeting, and returned here,
accompanied by my very kind friends, John and Tabitha Bevans,
whose company and help in the work,
together with the great kindness I experienced under their hospitable roof,
both from themselves and their three daughters,
I hope long to retain in grateful remembrance; and as I believe my beloved friends,
parents and children, were much disposed to aid me, a poor pilgrim,
in the name of a disciple,
may they be permitted to receive a reward for the work`'s sake.
Though I feel indeed but an unprofitable servant; yet, with a humble heart,
I can acknowledge that notwithstanding some of the closest baptisms I ever passed through,
were permitted me while with them, I also knew some seasons of heavenly favour;
I think some, wherein my mind was as nearly united to the beloved of souls,
as at any time in my life.
Yesterday morning,
after a religious opportunity with the two handmaids in J. Bevans`' family,
who are not in profession with us, my mind could rejoice in believing, beyond a doubt,
that the allotted portion of labour in that part was finished.
Then I thankfully felt it to be an eternal truth,
that though many are the afflictions of those who
are sent forth on the Great Master`'s errands,
yet as the heart is kept singly dependent on his arm of power,
he will most assuredly deliver out of them all; and grant a crown of life,
as a reward to all who are faithfully engaged to hold out to the end, in doing his will.
Thus, after the various conflicting seasons hitherto permitted me to experience,
I am enabled to thank you,
Oh Father! for your mercies past, and humbly hope for your gracious protection,
under every future dispensation of your will.

Fourth-day, 4th. Today is the monthly meeting at Grace-Church-Street;
and for some days past I have been endeavouring to
know whether it would be right for me to attend it;
but I have not been able to see any light upon going;
and feeling much indisposed in my health, a day or two of rest under this roof,
my cousin William Forster`'s, is very salutary to my enfeebled frame.
As I have not seen my way to go to London today,
I have forwarded my certificate to J. G. Bevan, to present it to the monthly meeting;
though I undoubtedly believe it will be right for me to finish
my engagements in this part before I leave this place again;
and as my friend Alice Chorley, an elder of this meeting,
has kindly proposed accompanying me for a few days,
I hope to be enabled to enter afresh into this field
of labour after the monthly meeting here tomorrow.

Thus far, in the accomplishment of the arduous prospect with which I left home,
I have had abundant cause to acknowledge, that all things needful have,
to my humbling admiration, been provided; and therefore,
I dare not distrust the bountiful hand which has already dispensed so liberally.
However, awful indeed does the approaching engagement appear,
of going among the largest body of Friends I have ever visited, in this individual way,
without the most distant expectation of a companion in the work;
but I marvel to find the calm resignation,
which my mind is mercifully favoured at times to experience,
in looking towards this important part of my present mission.
Yes, I am ready to believe,
that nothing short of the sustaining Arm of everlasting mercy,
could uphold me under what I now have in view.
I therefore feel bound to adore Him, committing myself once more to his holy guidance.

Fifth-day morning, 5th of the second month.
J+++.+++ G. Bevan has just been here, and informed me, on returning my certificate,
that their monthly meeting is adjourned till next fourth-day, which gives me concern,
having no expectation of being liberated from these parts, so soon as that time; but,
for the present, I wish to leave much thoughtfulness on this subject,
endeavouring to do what appears right in my allotment in this part of the work.

Evening.
At the meetinghouse today, I met a letter from my friend Mary Pryor,
in which she expresses herself in these words;--"`Believing a necessity laid on me,
I venture to offer accompanying you on your visit
to the families of Grace-Church-Street meeting.`"
So unexpected a proposal, and one so truly acceptable,
raised a tribute of thankfulness in my heart to Him, who I humbly trust, has bound this,
my dear ancient friend, again to evince her attachment to his pure cause,
and unite with a little sister in this great work.

Tottenham, fourth-day,
11th. Today I have attended the adjourned monthly meeting at Grace-Church-Street,
where I informed my friends of the prospect I have of a companion,
who is not likely to be at liberty from her own monthly meeting, before this day week;
and also that I did not feel myself at present fully clear of this quarter.
My information was cordially received,
and Friends kindly adjourned again until fifth-day, the 19th, for our accommodation;
which feels relieving to my mind,
believing by that time I shall be favoured to see my way to depart hence;
where I have for a long time been very affectionately cared for,
by my much esteemed friends and relatives of this family.

Southgate, fourth-day,
18th. I have now visited all the meetings and families
of Friends in Tottenham monthly meeting,
except two or three individuals, who are not at home, and a few others,
who do not incline to receive such a visit.
I have also had a few public meetings; the last was held yesterday evening at Mimms,
in a meetinghouse belonging to Friends.

In the course of my engagements in this quarter,
mourning and lamentation have been much more frequently the covering of my spirit,
than anything like rejoicing.
Yet, I verily believe, there is a precious few,
who are sweetly preserved loyal to the King of kings.
May their hands grow stronger and stronger in the holy warfare;
and may the number of upright-hearted standard-bearers, be increased among them.

Fourth-day, 4th of third month.
We have now been nearly two weeks very closely engaged in our arduous service
of visiting the families of Friends in Grace-Church-Street monthly meeting,
and my beloved and honourable companion and myself,
have hitherto been enabled to move along in much harmony and concord.
I feel it very relieving to my exercised, and often deeply tried mind,
to have the company and help of one whose religious
experience has been much larger than my own.
One who, after so long a warfare under the banner of the Captain of salvation,
can frequently testify that he is worthy to be obeyed to the utmost of our ability;
that verily his "`yoke is easy,
and his burden light:`" Matt. 11:30. I think I never
could more feelingly subscribe to the same gracious truth,
than since the commencement of the present engagement; for though, at times,
the faithful labourer must be brought into a state of bondage,
when and where the pure seed is kept in captivity;
yet it is a favour to be found worthy to suffer with a suffering Lord.
I believe all the exercises which dedicated minds may be permitted to pass through,
for themselves and for others, are not so great as those which are often imposed,
by the enemy of all good,
upon such as are pursuing the vain and delusive pleasures of the world.

Second-day, 16th of third month.
Yesterday my much beloved companion left me,
after our attending the morning meeting at Grace-Church-Street,
and having a solid season of religious retirement, at Joseph Savory`'s,
where we were nearly a month very kindly cared for, by him, his wife, and daughter Mary.
Mary Pryor went that evening to Hertford,
in order to attend the select quarterly meeting there, in the evening.
We were favoured to part under a feeling of that unity,
which had been mercifully vouchsafed to us during our late engagement.
A tribute of humble gratitude was raised in our hearts
to the bountiful giver of every blessing,
for the support which had been from time to time granted us; and for the holy aid which,
in a peculiar manner, was in some families dispensed to us,
to advocate his precious cause.
This, on the bended knees, was vocally acknowledged by my dear friend,
and heartily subscribed unto by myself, in prostration of soul before the Most High:
and a song of praise lived in my heart through the remaining part of the day.

Tomorrow I expect to reach Colchester, where, the next day,
I hope to meet my dear friend Martha Brewster, who is liberated by her friends at home,
to accompany me through the families in that monthly meeting,
and to visit some other meetings in Essex.

Colchester, seventh-day, 28th of the third month.
We have nearly got through our visit to the families of Friends in this monthly meeting.
And my beloved companion M. B. and myself,
have harmonized in our feeble endeavours to promote
the holy cause among our fellow professors hereabouts;
many of whom we cannot but covet may know an increased dedication
of heart to the pure unfoldings of heavenly love.
By this means,
they would become strengthened to stand faithful
to the various testimonies given us as a people,
to uphold to the world.
We have felt our minds animated and comforted in beholding the upright zeal,
which clothes our ancient and honourable friend and father in the church,
dear John Kendall,
under whose roof we have been kindly accommodated during our tarriance here.

On second-day the 30th, we left Colchester, and went to Dunmow, where, the next day,
we attended a monthly meeting, and taking meetings in our way at Stanstead, Bardfield,
and Sudbury, we reached Ipswich on second-day, the 6th of fourth month.
On third-day, we attended the monthly meeting there, when I delivered up my certificate;
and had cause to acknowledge,
that although I had passed through some very pinching trials,
and some seasons of close exercise; yet,
that Holy help has been near in the time of need.
In the remembrance thereof,
my soul feels renewedly bowed in thankfulness to the great Author of every blessing.

I returned home on fourth-day the 8th;
and though the sensible enjoyment of divine acceptance is much withheld, I feel,
at times, ability to adopt the language of the psalmist, where he says: "`Bless the Lord,
my soul; and all that is within me, bless his holy name.
Bless the Lord, O my soul, and forget not all his benefits;`" Ps. 103:1-2.
