== Supplement by the Editor

[.chapter-subtitle--blurb]
Containing some account of her last journey, also of her illness and decease.

The reader will probably have noticed a considerable chasm between the two last chapters;
for concerning this period the Editor does not find any memorandum of her own.
This might arise from her not being particularly engaged in advocating
that cause which she evinced to be so dear to her;
yet there is reason to believe, that during this, and the remaining time,
of which she relates but few occurrences,
her mind was preparing for the engagement in which she closed her faithful labours.

Although much gospel service was not her allotment in these periods,
yet she was very usefully occupied; many times, and on various occasions,
in kind assistance to some of her near relatives,
whose situation claimed her skilful care, as an affectionate nurse and attendant.
One of these was our beloved neice, Lucy Barton,
whom she attended at the time of her decease, in the summer of 1808.^
footnote:[For an account of Lucy Barton, see the 10th part of Piety Promoted.]

I come now to relate some particulars of her last religious journey,
the sequel of which deeply affects my heart; yet, I hope,
with resignation to unerring Wisdom,
who has seen fit to cut her work short in righteousness.

She left home with the full unity and concurrence of her friends,
on the 26th of the tenth month, 1809,
under a concern to visit the families of Friends at Worcester,
and to hold some meetings in those parts.
She was accompanied to Worcester by her brother and sister Jesup.
In a letter to her brother Samuel, from Warwick,
after speaking of two Friends calling on her at Bury at Martha Brewster`'s, she says,

[.embedded-content-document.letter]
--

Before we left that quiet dwelling,
my beloved M. B. in a little season of solid retirement, had a morsel to hand,
which proved to my deeply discouraged mind, for some hours after, truly consoling: yet,
I have repeatedly, since that time, experienced my faith to be, as it were,
smaller than the grain of mustard seed;
and I have been almost ready to doubt the rectitude of my present undertaking.
At some other times a portion of holy aid has, in mercy,
been so far extended as to lead me to hope I have not run without being sent.

That evening we reached Hannah Evens`' hospitable habitation in good time for tea;
and were not entirely unexpected.
We stayed the meeting next day, and left Godmanchester about two o`'clock,
for Wellingborough; where, from a letter I hope you received from Elizabeth Wheeler,
I suppose you had anticipated an awful meeting with our
beloved friends Benjamin Middleton and his daughters.
We had not obtained the smallest intimation of the
situation of the family till we got into the house,
when we were met by cousin Wheeler,
whose countenance plainly indicated something important.

Greatly surprised we were, on being informed that, after two weeks`' illness,
our much esteemed friend, Tabitha Middleton, had, last fourth-day,
closed her valuable life.
Dear Benjamin and his children received us with much composure,
and we spent a very interesting evening in the house of mourning.
Before we left them this morning, I felt bound to yield to a season of retirement,
and in it to offer the tribute of sympathy which lived in my heart towards them,
accompanied with a persuasion,
that not only a glorious mansion was prepared for the dear deceased;
but that those who remained to lament her departure,
were in a particular manner under the protecting wing of ancient Goodness.

--

At Worcester she was joined by William Forster, Jr.,
(then in those parts on religious service) with a view of entering upon
the arduous engagement of visiting Friends of that city in their families.
At a monthly meeting held there the 25th of the tenth month,
they presented their certificates, and opened their prospects,
which met the concurrence of Friends.
The next morning they entered upon the work; and proceeded without intermission,
as to any other religious engagement, till the first-day week following,
the 5th of the eleventh month;
when they had a large public meeting in Friends`' meeting-house, appointed with a view,
principally, to the lower class of the inhabitants of that place.
The next evening they had a meeting in a parish on the other side of the river;
and on third-day morning the 7th,
attended another public meeting in Friends`' meeting-house appointed
under a concern for the higher classes of the people.
That evening they finished the family visit in Worcester.
The testimonial sent from that monthly meeting to
the monthly meeting of which she was a member,
may be the best criterion,
by which to judge of the satisfaction this visit afforded to her friends.
An extract from it will be found at the close of this account.

As her labours, at this period, were hastening to a close,
perhaps a minute recital of the occupation of her time,
though sometimes unattended with any particular observations,
may be acceptable to the reader.

On fourth-day morning, the 8th of the eleventh month, W. Forster, Jr. and herself,
attended a public meeting at Malvern, and one in the evening at Upton on Severn;
and that night went to Tewksbury.
On fifth-day forenoon, they were at a meeting of Friends of that town;
had a meeting at Pershore that evening, and reached Evesham the same night.
On sixth-day evening they had a meeting on the premises of a Friend at Netherton,
about four miles from Evesham.
The next morning they returned there, and called upon several Friends in their families;
and that evening were at a public meeting, a mile and a half out of the town.

On first-day morning the 12th, they were at a meeting with Friends at Evesham;
and in Friends`' meeting-house, in the evening,
they had a very crowded meeting with the inhabitants.
Before she went to bed, my dear sister felt herself much indisposed,
but did not make much complaint.
The next day her companion thought her very unwell;
but in the afternoon they went to Alcester, and in the evening,
attended a large and satisfactory meeting in the Town-Hall; towards the close of which,
she was engaged in solemn supplication.
They walked nearly a mile to a Friend`'s house to lodge.
There she appeared much exhausted with fatigue, went to bed very unwell,
and passed a restless night.
The next morning the 14th, they returned into the town,
and had three sittings among Friends in their families, in which, although very unwell,
she took an acceptable part.
In the afternoon, they returned to the Friend`'s house at which they had lodged;
and in the evening, had an opportunity in the family,
in which she was strengthened to labour under considerable exercise of mind.
She was rather more unwell before she went to bed, and had another poor night.
Two meetings were appointed for the following day, the 15th,
and it was pretty much concluded, over night,
for her to give up that in the morning at Broomsgrove,
and to meet William in the evening at Droitwich.

On arriving at the latter place, however, he was surprised and affected to find that,
accompanied by Candia Burlingham, who had been her companion since leaving Evesham,
she was gone on to Worcester in a post-chaise; finding herself so ill,
as to wish to get on as fast as she could.
They arrived at Worcester in the evening, where she was violently affected with sickness,
but her complaint was deemed bilious, as she was subject to such a disorder.
The night she passed without much sleep; and the next morning an eruption appeared.
She first discovered it herself and said, "`Surely I have got the small-pox,`" adding,
"`I believe I know when I took it;
from a little child whom I met in the street previously to leaving Worcester.`"
An apothecary was called in, who pronounced the disorder to be the small-pox.
He thought she had treated herself judiciously,
and spoke very encouragingly of the symptoms.
Her sister Jesup, who was returned to Worcester from a visit in Wiltshire,
also thought it of a large and favourable sort.

She did not appear at all alarmed at finding the disorder was the small-pox; although,
in early life, she had felt much dread of it;
but expressed great concern at the trouble she was likely
to bring on her cousins Thomas and Eliza Burlingham`'s family,
feeling very tenderly for them.
That afternoon William Forster, Jr., who was about to write to one of her brothers,
at her request, went up and sat awhile with her.
She desired her very dear love to her brother and sister, and wished William to say,
"`That although she had passed through a greater degree of exercise and
suffering than ever she had experienced in the same space of time,
accompanied with less evidence of divine acceptance; yet, that afternoon,
she thought she had been favoured with a precious evidence,
that she had been there (alluding to her late visit) in better wisdom than her own.
This, she said, had tended to quiet the anxiety with which she was at first tried,
in considering the difficulty and perplexity she might occasion to others;
and she humbly trusted it might prove as a little
anchorage to her mind in seasons of future tossing.`"

She further remarked that it looked probable she might get through the disorder;
but added, "`I feel no wish respecting it.`"
On William Forster, Jr. asking her, just before he left the room, how she was,
she replied, "`I am as comfortable as I can be.`"
At that time she was quite free from pain, except a little fulness in her throat.

In the evening, speaking of the public meeting at Alcester,
she remarked what a comfortable one it was, and said,
"`I little thought it would be the last.`"
Then pausing awhile, added, "`Probably.`"
She then observed that it was trying to her to be so far from her relations; but added,
"`The cause is dearer to me than my natural life.`"

As soon as her complaint was determined to be the small-pox,
her cousins T. and E. Burlingham left their house and went over the way to his father`'s,
on account of their infant son.
The next morning, sixth-day the 17th, some family arrangements were made,
which in addition to the kindness and cheerfulness with which her
dear relatives gave up their house for her accommodation,
appeared quite to relieve her mind from all anxiety.

After this her head and throat became very painful; and the difficulty of swallowing,
and even of breathing, was very alarming;
and she herself thought she should never be able to swallow again; but,
by proper application, these symptoms were much relieved.

At different times, in the course of her deeply trying illness, she would say,
"`It would be a kindness to let me sink quietly away,
rather than keep me in this state of suffering;`" yet she frequently
expressed herself very gratefully to those who nursed her;
sometimes saying, "`she hoped they would be rewarded for their tenderness and care,
better than she could reward them.`"
She was favoured with much serenity and resignation throughout,
and appeared to have nothing of importance, either of spirituals or temporals,
to claim her attention.

Four days after the crisis of the disorder,
she told her medical attendant she got no better; and on the following day,
she desired that her relations might be informed, with her dear love,
that she felt her weakness daily increase,
and thought she should hardly be likely to see them any more.
Her weakness not being greater than the apothecary expected,
and no unfavourable symptoms appearing, he did not apprehend any cause for alarm;
on the contrary, on being interrogated, at different times,
he had always expressed himself favourably as to her getting through.

The next day, the 29th, her disorder put on a very unfavourable appearance,
and further advice was immediately procured;
but the physician did not think so unfavourably of her as the surgeon.
That evening and the next morning, by the means used for her relief,
there was so much improvement, that her medical attendants, and those around her,
flattered themselves with hopes of her recovery.
She passed through fifth-day night, the 30th, as favourably as could be expected;
but did not appear so well the next morning as such
a night led her attendants to hope for;
and in the forenoon, she seemed to be sinking fast, and thought herself going.
She asked the hour of the day, and being told it was half past twelve o`'clock,
she wished to know if the doctor had been there, and what he thought of her.
Being informed that he found her not so well as he had hoped for; after a short pause,
she said: "`There is no probability, no probability, of my struggling through:
what a favour it would be to be taken now, rather than suffer as I have done,
day after day, and night after night.`"
She then asked her sister if she was willing to give her up, and added,
"`What a comfort it has been to me that you have been with me.`"
Upon her sister asking her if she had any particular message to anyone, she replied, "`No!
My dear, dear love to all,--to all,`" adding, "`and to all your children;
I love them all very dearly.`"
She then further said, "`I hope my poor soul will be saved.
A place in the smallest mansion is all I ask.
A place in the smallest mansion is all I ask.`"

She was fully satisfied with the doctor and apothecary; and that afternoon,
having revived again about the time of their coming,
she told them she hoped they would be rewarded for their kindness towards her,
both in this world and that to come.
On account of the disorder, her relations T. and E. Burlingham,
had been 1 obliged to keep from her till their infant child had been vaccinated.
That evening, Thomas came to her; she knew him, took him by the hand,
and expressed herself very affectionately to him.

On seventh-day morning early she relapsed again; and in the forenoon of that day,
she asked the apothecary if he thought her close was near.
He replied, "`he thought it was.`"
She answered, "`What a favour!`"
In the afternoon she said, "`It is marvellous to me I am so long in dying;
it is not common, I think.`"
Some time afterwards, she said, "`The spirit cannot depart; the spirit cannot depart.
Blessed--blessed.`"
At another time: "`It will not do, the time is not yet come.`"
After that, to the admiration of her medical attendants, and all around her,
she revived again and took nourishment freely.

On first-day, the 3rd of twelfth month,
she changed several times in the course of the day; and in the evening,
being informed that her brother Samuel was come, she wished him to come to her;
but desired he might be informed she was a poor creature to visit,
and could say but little.
Going to her, she took his hand and turned her face towards him,
seeming to try to look at him,
(for she had been several days blind) and spoke affectionately,
but only a few words intelligibly.
She was soon informed that her brother Dykes, and her niece Lucy Maw,
were also in the room.
She spoke to the latter, and seemed to intimate her wish to speak to her brother Dykes,
but her weakness so increased just then, that she could not articulate;
yet she gave afterwards several clear proofs of knowing that her relations were present.
In the course of the evening she laboured under great distress from the load of disease,
and often said, "`Dear, oh dear,`" arising from the extremity of her suffering;
yet these expressions were evidently under a sense of care, to avoid,
either in word or manner, murmuring at the last trying conflict of nature.

Her brothers and niece were thankful in being permitted to see her living;
not only for their own satisfaction,
but from a secret belief that her knowing they were there,
afforded her mind a little comfort under her deeply trying conflict.
During this last struggle of nature, at several different times,
she held up her hands as in the attitude of prayer; and about half past three,
on second-day morning, the 4th of the twelfth month, she quietly breathed her last.

Her remains were interred at Worcester, on the fifth-day following.
She was about 50 years of age, and had been a minister about 21 years.

Perhaps I cannot more suitably close these memoirs,
than by the concluding words of the testimonial sent
from Worcester monthly meeting to her own;
and which were adopted by the latter monthly meeting in the testimony addressed
to the yearly meeting:--"`We may weep over her as a friend or as a relation;
we may mourn the loss which the church has sustained of one of her upright pillars; but,
on her account, there appears no cause for sorrow.
She was, we believe, favoured to finish all she had in commission;
showing herself therein a good and faithful servant.
The great reward of faithfulness was permitted to follow, in quick succession,
her allotted portion of labour; and we doubt not she is entered into the joy of her Lord,
and into her Master`'s rest.`"
